<script setup lang="ts">
import { createId } from '../../domain/factories'
import type { Material, MaterialResourceType, WorkshopPlan } from '../../domain/types'
const props = defineProps<{ plan: WorkshopPlan }>(); const emit = defineEmits<{ changed: [] }>()
function add(): void { props.plan.materials.push({ id: createId(), name: '', resourceType: 'physical' }); emit('changed') }
function remove(material: Material): void { props.plan.materials = props.plan.materials.filter((item) => item.id !== material.id); props.plan.schedule.forEach((entry) => entry.materialIds = entry.materialIds.filter((id) => id !== material.id)); emit('changed') }
const types: MaterialResourceType[] = ['physical', 'file', 'worksheet', 'link', 'interactive-html']
</script>
<template><section class="section-card"><div class="section-heading with-action"><div><p class="eyebrow">Ressourcen</p><h1>Materialien</h1><p>Materialien werden zentral gepflegt und koennen mehreren Phasen zugeordnet werden.</p></div><button type="button" @click="add">+ Material</button></div><div class="materials-table"><div class="materials-header"><span>Name</span><span>Menge</span><span>Typ</span><span>Beschreibung</span><span /></div><div v-for="material in plan.materials" :key="material.id" class="materials-row"><input v-model="material.name" placeholder="z. B. Moderationskarten" @change="emit('changed')"><input v-model="material.quantity" placeholder="Anzahl" @change="emit('changed')"><select v-model="material.resourceType" @change="emit('changed')"><option v-for="type in types" :key="type" :value="type">{{ type }}</option></select><input v-model="material.description" placeholder="optional" @change="emit('changed')"><button type="button" class="danger" aria-label="Material entfernen" @click="remove(material)">×</button></div></div></section></template>
