<script setup lang="ts">
import { createId } from '../../domain/factories'
import type { WorkshopDay, WorkshopPlan } from '../../domain/types'
const props = defineProps<{ plan: WorkshopPlan }>(); const emit = defineEmits<{ changed: [] }>()
function add(): void { props.plan.days.push({ id: createId(), date: new Date().toISOString().slice(0, 10) }); emit('changed') }
function remove(day: WorkshopDay): void { if (props.plan.days.length === 1) return; props.plan.days = props.plan.days.filter((item) => item.id !== day.id); props.plan.schedule = props.plan.schedule.filter((entry) => entry.dayId !== day.id); emit('changed') }
function move(index: number, direction: number): void { const target = index + direction; if (target < 0 || target >= props.plan.days.length) return; [props.plan.days[index], props.plan.days[target]] = [props.plan.days[target], props.plan.days[index]]; emit('changed') }
</script>
<template><section class="section-card"><div class="section-heading with-action"><div><p class="eyebrow">Zeitraum</p><h1>Termine</h1><p>Eine Planung kann einen oder mehrere Veranstaltungstage enthalten.</p></div><button type="button" @click="add">+ Tag hinzufügen</button></div><div class="day-list"><article v-for="(day, index) in plan.days" :key="day.id" class="day-card"><div class="day-number">Tag {{ index + 1 }}</div><div class="form-grid compact"><label>Datum<input v-model="day.date" type="date" @change="emit('changed')"></label><label>Bezeichnung<input v-model="day.title" placeholder="z. B. Exkursion" @change="emit('changed')"></label><label>Beginn<input v-model="day.startTime" type="time" @change="emit('changed')"></label><label>Ende<input v-model="day.endTime" type="time" @change="emit('changed')"></label></div><div class="row-actions"><button type="button" :disabled="index === 0" title="Nach oben" @click="move(index, -1)">↑</button><button type="button" :disabled="index === plan.days.length - 1" title="Nach unten" @click="move(index, 1)">↓</button><button type="button" class="danger" :disabled="plan.days.length === 1" @click="remove(day)">Entfernen</button></div></article></div></section></template>
