<script setup lang="ts">
import { createId } from '../../domain/factories'
import type { LearningObjective, WorkshopPlan } from '../../domain/types'
const props = defineProps<{ plan: WorkshopPlan }>(); const emit = defineEmits<{ changed: [] }>()
function add(): void { props.plan.learningObjectives.push({ id: createId(), text: '', competencyIds: [] }); emit('changed') }
function remove(objective: LearningObjective): void { props.plan.learningObjectives = props.plan.learningObjectives.filter((item) => item.id !== objective.id); emit('changed') }
function move(index: number, direction: number): void { const target = index + direction; if (target < 0 || target >= props.plan.learningObjectives.length) return; [props.plan.learningObjectives[index], props.plan.learningObjectives[target]] = [props.plan.learningObjectives[target], props.plan.learningObjectives[index]]; emit('changed') }
</script>
<template><section class="section-card"><div class="section-heading with-action"><div><p class="eyebrow">Wirkung</p><h1>Lernziele</h1><p>Formulieren Sie, was Teilnehmende am Ende können, beurteilen oder erstellen.</p></div><button type="button" @click="add">+ Lernziel</button></div><div class="stack-list"><div v-for="(objective, index) in plan.learningObjectives" :key="objective.id" class="objective-row"><span aria-hidden="true">☷</span><textarea v-model="objective.text" rows="2" placeholder="Die Teilnehmenden können ..." @change="emit('changed')" /><input v-model="objective.level" placeholder="Operator / Niveau" @change="emit('changed')"><button type="button" :disabled="index === 0" @click="move(index, -1)">↑</button><button type="button" :disabled="index === plan.learningObjectives.length - 1" @click="move(index, 1)">↓</button><button type="button" class="danger" aria-label="Lernziel entfernen" @click="remove(objective)">×</button></div><p v-if="!plan.learningObjectives.length" class="empty-state">Noch keine Lernziele. Beginnen Sie mit einem beobachtbaren Satz.</p></div></section></template>
