import { randomUUID } from 'node:crypto'
import { mkdtempSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { describe, expect, it } from 'vitest'
import { SqliteSchoolPlanning } from './schoolPlanning'
import { SqlitePlans } from './sqlitePlans'

const stamp = '2026-09-30T12:00:00.000Z'
const schoolYear = (id = randomUUID()) => ({ id, name: '2026/27', federalState: 'TH' as const, schoolType: 'Gymnasium', startDate: '2026-08-01', endDate: '2027-07-31', active: true, createdAt: stamp, updatedAt: stamp })

describe('relationale Schuljahresplanung', () => {
  it('speichert Schuljahr, Parallelklassen, Fachzuordnungen und getrennte Lehrplanmarker', () => {
    const database = new SqliteSchoolPlanning(join(mkdtempSync(join(tmpdir(), 'verlaufsplaner-school-planning-')), 'planning.sqlite'))
    const year = database.saveSchoolYear(schoolYear())
    const firstClass = database.saveClassGroup({ id: randomUUID(), schoolYearId: year.id, name: '8a', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp })
    const secondClass = database.saveClassGroup({ id: randomUUID(), schoolYearId: year.id, name: '8b', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp })
    const firstAssignment = database.saveAssignment({ id: randomUUID(), classGroupId: firstClass.id, schoolYearId: year.id, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp })
    const secondAssignment = database.saveAssignment({ id: randomUUID(), classGroupId: secondClass.id, schoolYearId: year.id, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp })
    const firstAnnotation = database.saveAnnotation({ id: randomUUID(), classSubjectAssignmentId: firstAssignment.id, curriculumNodeId: 'history-vormaerz', nodeKind: 'content-point', status: 'rough-planned', plannedWeek: 36, createdAt: stamp, updatedAt: stamp })
    database.saveAnnotation({ id: randomUUID(), classSubjectAssignmentId: secondAssignment.id, curriculumNodeId: 'history-vormaerz', nodeKind: 'content-point', status: 'completed', createdAt: stamp, updatedAt: stamp })
    const sequence = database.saveSequence({ id: randomUUID(), classSubjectAssignmentId: firstAssignment.id, title: 'Vormärz – Freiheit und nationale Einheit', status: 'planned', startDate: '2026-09-04', endDate: '2026-09-26', createdAt: stamp, updatedAt: stamp })
    database.saveAnnotation({ ...firstAnnotation, status: 'scheduled', teachingSequenceId: sequence.id, updatedAt: stamp })
    database.saveSequenceCurriculumReference({ id: randomUUID(), teachingSequenceId: sequence.id, curriculumNodeId: 'th-gym-history-2021-g7-8', nodeKind: 'learning-area', relationType: 'primary', createdAt: stamp, updatedAt: stamp })
    database.saveSequenceCompetency({ id: randomUUID(), teachingSequenceId: sequence.id, competencyId: 'th-gym-history-2021-comp-method', role: 'primary', createdAt: stamp, updatedAt: stamp })
    const sequenceLesson = database.saveSequenceLesson({ id: randomUUID(), teachingSequenceId: sequence.id, position: 1, plannedDate: '2026-09-04', plannedDuration: 45, title: 'Historische Lieder', differentiation: 'Hilfekarten und Vertiefungsauftrag.', digitalTools: 'Quellenboard', technicalRequirements: 'Beamer und WLAN', fallbackPlan: 'Ausgedruckte Quellenauszüge', status: 'planned', createdAt: stamp, updatedAt: stamp })
    const scheduledLesson = database.saveScheduledLesson({ id: randomUUID(), classSubjectAssignmentId: firstAssignment.id, sequenceLessonId: sequenceLesson.id, date: '2026-09-04', startTime: '08:00', endTime: '08:45', contextType: 'REGULAR_LESSON', status: 'planned', createdAt: stamp, updatedAt: stamp })
    database.saveScheduledLesson({ ...scheduledLesson, date: '2026-09-05', startTime: '09:00', updatedAt: stamp })
    const timetableVersion = database.saveTimetableVersion({ id: randomUUID(), schoolYearId: year.id, name: 'Regelstundenplan ab Herbstferien', validFrom: '2026-10-12', active: true, createdAt: stamp, updatedAt: stamp })
    const timetableSlot = database.saveTimetableSlot({ id: randomUUID(), timetableVersionId: timetableVersion.id, classSubjectAssignmentId: firstAssignment.id, weekday: 2, startTime: '08:00', endTime: '08:45', room: 'R 204', contextType: 'REGULAR_LESSON', createdAt: stamp, updatedAt: stamp })
    database.saveCalendarException({ id: randomUUID(), schoolYearId: year.id, classSubjectAssignmentId: firstAssignment.id, timetableSlotId: timetableSlot.id, date: '2026-10-20', type: 'CANCELLATION', title: 'Wandertag 8a', note: 'Keine Geschichtsstunde.', createdAt: stamp, updatedAt: stamp })
    database.saveLessonReflection({ id: randomUUID(), sequenceLessonId: sequenceLesson.id, outcome: 'needs-revisit', note: 'Zu wenig Zeit für die Sicherung.', objectivesReached: false, deviations: 'Sicherung verkürzt.', timingNotes: 'Gruppenarbeit dauerte länger.', classNotes: 'Hohe Beteiligung.', sequenceImpact: 'Wiederholung einplanen.', nextLessonAdjustment: 'Einstieg kürzen.', repeatNeeded: true, createdAt: stamp, updatedAt: stamp })
    database.saveSequenceReflection({ id: randomUUID(), teachingSequenceId: sequence.id, coveredTopics: 'Vormärz und nationale Einheit', curriculumAreas: 'Geschichte 7/8', openTopics: 'Revolution 1848/49', competenciesToRevisit: 'Quellenkritik', lessonsToAdjust: 'Sicherung in Stunde 3', reuseMaterials: true, note: 'Bildanalyse wieder einsetzen.', createdAt: stamp, updatedAt: stamp })
    const copiedSequence = database.saveSequence({ ...sequence, id: randomUUID(), classSubjectAssignmentId: secondAssignment.id, title: 'Kopie für 8b', status: 'draft', createdAt: stamp, updatedAt: stamp })
    database.saveSequenceLesson({ ...sequenceLesson, id: randomUUID(), teachingSequenceId: copiedSequence.id, scheduledLessonId: undefined, planId: undefined, plannedDate: undefined, status: 'draft', createdAt: stamp, updatedAt: stamp })

    const snapshot = database.snapshot()
    expect(snapshot.schoolYears).toHaveLength(1)
    expect(snapshot.classGroups.map((group) => group.name)).toEqual(['8a', '8b'])
    expect(snapshot.annotations.filter((annotation) => annotation.classSubjectAssignmentId === firstAssignment.id)).toMatchObject([{ status: 'scheduled', plannedWeek: 36, teachingSequenceId: sequence.id }])
    expect(snapshot.annotations.filter((annotation) => annotation.classSubjectAssignmentId === secondAssignment.id)).toMatchObject([{ status: 'completed' }])
    expect(snapshot.sequences.filter((item) => item.classSubjectAssignmentId === firstAssignment.id)).toMatchObject([{ title: 'Vormärz – Freiheit und nationale Einheit', status: 'completed' }])
    expect(snapshot.sequenceCurriculumReferences).toMatchObject([{ teachingSequenceId: sequence.id, curriculumNodeId: 'th-gym-history-2021-g7-8', relationType: 'primary' }])
    expect(snapshot.sequenceCompetencies).toMatchObject([{ teachingSequenceId: sequence.id, competencyId: 'th-gym-history-2021-comp-method', role: 'primary' }])
    expect(snapshot.sequenceLessons.filter((item) => item.teachingSequenceId === sequence.id)).toMatchObject([{ title: 'Historische Lieder', plannedDuration: 45, digitalTools: 'Quellenboard', fallbackPlan: 'Ausgedruckte Quellenauszüge' }])
    expect(snapshot.scheduledLessons).toMatchObject([{ date: '2026-09-05', startTime: '09:00', contextType: 'REGULAR_LESSON' }])
    expect(snapshot.timetableVersions).toMatchObject([{ id: timetableVersion.id, validFrom: '2026-10-12', active: true }])
    expect(snapshot.timetableSlots).toMatchObject([{ timetableVersionId: timetableVersion.id, weekday: 2, room: 'R 204' }])
    expect(snapshot.calendarExceptions).toMatchObject([{ timetableSlotId: timetableSlot.id, date: '2026-10-20', type: 'CANCELLATION' }])
    expect(snapshot.lessonReflections).toMatchObject([{ sequenceLessonId: sequenceLesson.id, outcome: 'needs-revisit', objectivesReached: false, deviations: 'Sicherung verkürzt.', nextLessonAdjustment: 'Einstieg kürzen.', repeatNeeded: true }])
    expect(snapshot.sequenceReflections).toMatchObject([{ teachingSequenceId: sequence.id, openTopics: 'Revolution 1848/49', competenciesToRevisit: 'Quellenkritik', reuseMaterials: true }])
    expect(snapshot.sequences.filter((item) => item.id === sequence.id)).toMatchObject([{ status: 'completed' }])
    expect(snapshot.sequences.filter((item) => item.classSubjectAssignmentId === secondAssignment.id)).toMatchObject([{ title: 'Kopie für 8b', status: 'draft' }])
    expect(snapshot.sequenceLessons.filter((item) => item.teachingSequenceId === copiedSequence.id)).toMatchObject([{ title: 'Historische Lieder', scheduledLessonId: undefined, plannedDate: undefined, status: 'draft' }])
  })

  it('kaskadiert persönliche Annotationen mit ihrer Klassen-Fach-Zuordnung statt Referenzcurricula zu verändern', () => {
    const database = new SqliteSchoolPlanning(join(mkdtempSync(join(tmpdir(), 'verlaufsplaner-school-planning-')), 'planning.sqlite'))
    const year = database.saveSchoolYear(schoolYear())
    const group = database.saveClassGroup({ id: randomUUID(), schoolYearId: year.id, name: '8a', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp })
    const assignment = database.saveAssignment({ id: randomUUID(), classGroupId: group.id, schoolYearId: year.id, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp })
    database.saveComment({ id: randomUUID(), classSubjectAssignmentId: assignment.id, curriculumNodeId: 'history-vormaerz', comment: 'Bildanalyse einplanen.', resolved: false, createdAt: stamp, updatedAt: stamp })
    expect(database.snapshot().comments).toHaveLength(1)
    expect(database.remove('class_subject_assignments', assignment.id)).toBe(true)
    expect(database.snapshot().comments).toHaveLength(0)
    expect(database.snapshot().schoolYears).toHaveLength(1)
  })

  it('kaskadiert relationale Lehrplan- und Kompetenzbezüge beim Löschen einer Reihe', () => {
    const database = new SqliteSchoolPlanning(join(mkdtempSync(join(tmpdir(), 'verlaufsplaner-school-planning-')), 'planning.sqlite'))
    const year = database.saveSchoolYear(schoolYear())
    const group = database.saveClassGroup({ id: randomUUID(), schoolYearId: year.id, name: '8a', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp })
    const assignment = database.saveAssignment({ id: randomUUID(), classGroupId: group.id, schoolYearId: year.id, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp })
    const sequence = database.saveSequence({ id: randomUUID(), classSubjectAssignmentId: assignment.id, title: 'Vormärz', status: 'planned', createdAt: stamp, updatedAt: stamp })
    database.saveSequenceCurriculumReference({ id: randomUUID(), teachingSequenceId: sequence.id, curriculumNodeId: 'th-gym-history-2021-g7-8', nodeKind: 'learning-area', relationType: 'primary', createdAt: stamp, updatedAt: stamp })
    database.saveSequenceCompetency({ id: randomUUID(), teachingSequenceId: sequence.id, competencyId: 'th-gym-history-2021-comp-method', role: 'supporting', createdAt: stamp, updatedAt: stamp })
    database.saveSequenceReflection({ id: randomUUID(), teachingSequenceId: sequence.id, openTopics: 'Vertiefung', reuseMaterials: false, createdAt: stamp, updatedAt: stamp })
    expect(database.snapshot().sequenceCurriculumReferences).toHaveLength(1)
    expect(database.snapshot().sequenceCompetencies).toHaveLength(1)
    expect(database.remove('teaching_sequences', sequence.id)).toBe(true)
    expect(database.snapshot().sequenceCurriculumReferences).toHaveLength(0)
    expect(database.snapshot().sequenceCompetencies).toHaveLength(0)
    expect(database.snapshot().sequenceReflections).toHaveLength(0)
  })

  it('keeps markers and edited comments separate for parallel classes', () => {
    const database = new SqliteSchoolPlanning(join(mkdtempSync(join(tmpdir(), 'verlaufsplaner-school-planning-')), 'planning.sqlite'))
    const year = database.saveSchoolYear(schoolYear())
    const firstClass = database.saveClassGroup({ id: randomUUID(), schoolYearId: year.id, name: '8a', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp })
    const secondClass = database.saveClassGroup({ id: randomUUID(), schoolYearId: year.id, name: '8b', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp })
    const firstAssignment = database.saveAssignment({ id: randomUUID(), classGroupId: firstClass.id, schoolYearId: year.id, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp })
    const secondAssignment = database.saveAssignment({ id: randomUUID(), classGroupId: secondClass.id, schoolYearId: year.id, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp })
    database.saveAnnotation({ id: randomUUID(), classSubjectAssignmentId: firstAssignment.id, curriculumNodeId: 'history-vormaerz', nodeKind: 'content-point', status: 'completed', plannedWeek: 42, createdAt: stamp, updatedAt: stamp })
    database.saveAnnotation({ id: randomUUID(), classSubjectAssignmentId: secondAssignment.id, curriculumNodeId: 'history-vormaerz', nodeKind: 'content-point', status: 'needs-revisit', plannedWeek: 8, createdAt: stamp, updatedAt: stamp })
    const comment = database.saveComment({ id: randomUUID(), classSubjectAssignmentId: firstAssignment.id, curriculumNodeId: 'history-vormaerz', comment: 'Add image analysis.', resolved: false, createdAt: stamp, updatedAt: stamp })
    database.saveComment({ ...comment, comment: 'Add image analysis and source criticism.', resolved: true, updatedAt: stamp })

    const snapshot = database.snapshot()
    expect(snapshot.annotations.filter((annotation) => annotation.classSubjectAssignmentId === firstAssignment.id)).toMatchObject([{ status: 'completed', plannedWeek: 42 }])
    expect(snapshot.annotations.filter((annotation) => annotation.classSubjectAssignmentId === secondAssignment.id)).toMatchObject([{ status: 'needs-revisit', plannedWeek: 8 }])
    expect(snapshot.comments.filter((entry) => entry.classSubjectAssignmentId === firstAssignment.id)).toMatchObject([{ id: comment.id, comment: 'Add image analysis and source criticism.', resolved: true }])
    expect(snapshot.comments.filter((entry) => entry.classSubjectAssignmentId === secondAssignment.id)).toEqual([])
  })

  it('ordnet vorhandene Plan-Payloads rückwärtskompatibel als Workshop ein, ohne sie zu verändern', () => {
    const path = join(mkdtempSync(join(tmpdir(), 'verlaufsplaner-school-planning-')), 'planning.sqlite')
    const planId = randomUUID()
    new SqlitePlans(path).save({ id: planId, metadata: { title: 'Bestehender Workshop' }, updatedAt: stamp, days: [{ date: '2026-09-04' }] })
    const database = new SqliteSchoolPlanning(path)
    expect(database.snapshot().existingPlanContexts).toMatchObject([{ planId, contextType: 'WORKSHOP' }])
  })

  it('bewahrt frühere Stundenplanversionen und speichert scoped Kalenderausnahmen', () => {
    const database = new SqliteSchoolPlanning(join(mkdtempSync(join(tmpdir(), 'verlaufsplaner-school-planning-')), 'planning.sqlite'))
    const year = database.saveSchoolYear(schoolYear())
    const group = database.saveClassGroup({ id: randomUUID(), schoolYearId: year.id, name: '8a', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp })
    const assignment = database.saveAssignment({ id: randomUUID(), classGroupId: group.id, schoolYearId: year.id, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp })
    const autumn = database.saveTimetableVersion({ id: randomUUID(), schoolYearId: year.id, name: 'Herbst', validFrom: '2026-08-01', validUntil: '2027-01-31', active: false, createdAt: stamp, updatedAt: stamp })
    const spring = database.saveTimetableVersion({ id: randomUUID(), schoolYearId: year.id, name: 'Frühjahr', validFrom: '2027-02-01', active: true, createdAt: stamp, updatedAt: stamp })
    const slot = database.saveTimetableSlot({ id: randomUUID(), timetableVersionId: spring.id, classSubjectAssignmentId: assignment.id, weekday: 1, startTime: '08:00', endTime: '08:45', contextType: 'REGULAR_LESSON', createdAt: stamp, updatedAt: stamp })
    database.saveCalendarException({ id: randomUUID(), schoolYearId: year.id, classSubjectAssignmentId: assignment.id, timetableSlotId: slot.id, date: '2027-03-15', type: 'HOLIDAY', title: 'Feiertag', createdAt: stamp, updatedAt: stamp })
    const snapshot = database.snapshot()
    expect(snapshot.timetableVersions).toMatchObject([{ id: spring.id, active: true }, { id: autumn.id, active: false }])
    expect(snapshot.timetableSlots).toMatchObject([{ timetableVersionId: spring.id, weekday: 1 }])
    expect(snapshot.calendarExceptions).toMatchObject([{ date: '2027-03-15', type: 'HOLIDAY', timetableSlotId: slot.id }])
  })
})
