import { DatabaseSync } from 'node:sqlite'
import { mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import type { CalendarException, ClassGroup, ClassSubjectAssignment, CurriculumAnnotation, CurriculumComment, ExistingPlanContext, LessonReflection, ScheduledLesson, SchoolPlanningSnapshot, SchoolYear, SequenceCompetency, SequenceCurriculumReference, SequenceLesson, TeachingSequence, TimetableSlot, TimetableVersion } from '../src/domain/schoolPlanning'

const databasePath = resolve(process.cwd(), 'data', 'verlaufsplaner.sqlite')
const now = () => new Date().toISOString()

/** Relational personal planning layer. It deliberately never stores curriculum reference data or plans as blobs. */
export class SqliteSchoolPlanning {
  private readonly database: DatabaseSync
  constructor(path = databasePath) {
    mkdirSync(dirname(path), { recursive: true })
    this.database = new DatabaseSync(path)
    this.database.exec(`PRAGMA foreign_keys = ON;
      CREATE TABLE IF NOT EXISTS school_years (id TEXT PRIMARY KEY, name TEXT NOT NULL, federal_state TEXT NOT NULL, school_type TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, school_id TEXT, active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL) STRICT;
      CREATE TABLE IF NOT EXISTS class_groups (id TEXT PRIMARY KEY, school_year_id TEXT NOT NULL REFERENCES school_years(id) ON DELETE CASCADE, name TEXT NOT NULL, grade INTEGER NOT NULL CHECK(grade > 0), school_type TEXT NOT NULL, students_count INTEGER, notes TEXT, accent TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL) STRICT;
      CREATE TABLE IF NOT EXISTS class_subject_assignments (id TEXT PRIMARY KEY, class_group_id TEXT NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE, subject_id TEXT NOT NULL, curriculum_id TEXT NOT NULL, school_year_id TEXT NOT NULL REFERENCES school_years(id) ON DELETE CASCADE, teacher_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(class_group_id, subject_id, school_year_id));
      CREATE TABLE IF NOT EXISTS curriculum_annotations (id TEXT PRIMARY KEY, class_subject_assignment_id TEXT NOT NULL REFERENCES class_subject_assignments(id) ON DELETE CASCADE, curriculum_node_id TEXT NOT NULL, node_kind TEXT NOT NULL, status TEXT NOT NULL, planned_week INTEGER, planned_start_date TEXT, planned_end_date TEXT, teaching_sequence_id TEXT, scheduled_lesson_id TEXT, priority TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(class_subject_assignment_id, curriculum_node_id));
      CREATE TABLE IF NOT EXISTS curriculum_comments (id TEXT PRIMARY KEY, class_subject_assignment_id TEXT NOT NULL REFERENCES class_subject_assignments(id) ON DELETE CASCADE, curriculum_node_id TEXT NOT NULL, selected_text TEXT, anchor_start INTEGER, anchor_end INTEGER, comment TEXT NOT NULL, resolved INTEGER NOT NULL CHECK(resolved IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS teaching_sequences (id TEXT PRIMARY KEY, class_subject_assignment_id TEXT NOT NULL REFERENCES class_subject_assignments(id) ON DELETE CASCADE, title TEXT NOT NULL, description TEXT, overarching_question TEXT, learning_goal TEXT, start_date TEXT, end_date TEXT, status TEXT NOT NULL, notes TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS sequence_curriculum_references (id TEXT PRIMARY KEY, teaching_sequence_id TEXT NOT NULL REFERENCES teaching_sequences(id) ON DELETE CASCADE, curriculum_node_id TEXT NOT NULL, node_kind TEXT NOT NULL, relation_type TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(teaching_sequence_id, curriculum_node_id));
      CREATE TABLE IF NOT EXISTS sequence_competencies (id TEXT PRIMARY KEY, teaching_sequence_id TEXT NOT NULL REFERENCES teaching_sequences(id) ON DELETE CASCADE, competency_id TEXT NOT NULL, role TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(teaching_sequence_id, competency_id));
      CREATE TABLE IF NOT EXISTS sequence_lessons (id TEXT PRIMARY KEY, teaching_sequence_id TEXT NOT NULL REFERENCES teaching_sequences(id) ON DELETE CASCADE, position INTEGER NOT NULL, scheduled_lesson_id TEXT, plan_id TEXT, planned_date TEXT, planned_duration INTEGER, title TEXT NOT NULL, guiding_question TEXT, lesson_objective TEXT, content_summary TEXT, competence_focus TEXT, curriculum_node_id TEXT, methods_summary TEXT, materials_summary TEXT, didactic_note TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(teaching_sequence_id, position));
      CREATE TABLE IF NOT EXISTS scheduled_lessons (id TEXT PRIMARY KEY, class_subject_assignment_id TEXT NOT NULL REFERENCES class_subject_assignments(id) ON DELETE CASCADE, sequence_lesson_id TEXT, plan_id TEXT, date TEXT NOT NULL, start_time TEXT, end_time TEXT, status TEXT NOT NULL, context_type TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS timetable_versions (id TEXT PRIMARY KEY, school_year_id TEXT NOT NULL REFERENCES school_years(id) ON DELETE CASCADE, name TEXT NOT NULL, valid_from TEXT NOT NULL, valid_until TEXT, active INTEGER NOT NULL CHECK(active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS timetable_slots (id TEXT PRIMARY KEY, timetable_version_id TEXT NOT NULL REFERENCES timetable_versions(id) ON DELETE CASCADE, class_subject_assignment_id TEXT NOT NULL REFERENCES class_subject_assignments(id) ON DELETE CASCADE, weekday INTEGER NOT NULL CHECK(weekday BETWEEN 1 AND 7), start_time TEXT NOT NULL, end_time TEXT NOT NULL, room TEXT, context_type TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS calendar_exceptions (id TEXT PRIMARY KEY, school_year_id TEXT NOT NULL REFERENCES school_years(id) ON DELETE CASCADE, class_subject_assignment_id TEXT REFERENCES class_subject_assignments(id) ON DELETE CASCADE, timetable_slot_id TEXT REFERENCES timetable_slots(id) ON DELETE CASCADE, date TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, replacement_start_time TEXT, replacement_end_time TEXT, note TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS lesson_reflections (id TEXT PRIMARY KEY, sequence_lesson_id TEXT NOT NULL REFERENCES sequence_lessons(id) ON DELETE CASCADE UNIQUE, outcome TEXT NOT NULL, note TEXT, repeat_needed INTEGER NOT NULL CHECK(repeat_needed IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS existing_plan_contexts (plan_id TEXT PRIMARY KEY REFERENCES plans(id) ON DELETE CASCADE, context_type TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_class_groups_school_year ON class_groups(school_year_id);
      CREATE INDEX IF NOT EXISTS idx_assignments_school_year ON class_subject_assignments(school_year_id);
      CREATE INDEX IF NOT EXISTS idx_annotations_assignment ON curriculum_annotations(class_subject_assignment_id);
      CREATE INDEX IF NOT EXISTS idx_annotations_status ON curriculum_annotations(status);
      CREATE INDEX IF NOT EXISTS idx_comments_assignment ON curriculum_comments(class_subject_assignment_id);
      CREATE INDEX IF NOT EXISTS idx_sequences_assignment ON teaching_sequences(class_subject_assignment_id);
      CREATE INDEX IF NOT EXISTS idx_sequence_curriculum_references_sequence ON sequence_curriculum_references(teaching_sequence_id);
      CREATE INDEX IF NOT EXISTS idx_sequence_competencies_sequence ON sequence_competencies(teaching_sequence_id);
      CREATE INDEX IF NOT EXISTS idx_sequence_lessons_sequence ON sequence_lessons(teaching_sequence_id);
      CREATE INDEX IF NOT EXISTS idx_scheduled_lessons_assignment_date ON scheduled_lessons(class_subject_assignment_id, date);
      CREATE INDEX IF NOT EXISTS idx_timetable_versions_school_year ON timetable_versions(school_year_id, valid_from);
      CREATE INDEX IF NOT EXISTS idx_timetable_slots_version_weekday ON timetable_slots(timetable_version_id, weekday);
      CREATE INDEX IF NOT EXISTS idx_calendar_exceptions_school_year_date ON calendar_exceptions(school_year_id, date);`)
    const plansTable = this.database.prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'plans'").get()
    if (plansTable) this.database.prepare("INSERT OR IGNORE INTO existing_plan_contexts (plan_id, context_type, created_at, updated_at) SELECT id, 'WORKSHOP', updated_at, updated_at FROM plans").run()
  }
  snapshot(): SchoolPlanningSnapshot {
    return {
      schoolYears: this.database.prepare('SELECT id, name, federal_state AS federalState, school_type AS schoolType, start_date AS startDate, end_date AS endDate, school_id AS schoolId, active, created_at AS createdAt, updated_at AS updatedAt FROM school_years ORDER BY start_date DESC').all() as unknown as SchoolYear[],
      classGroups: this.database.prepare('SELECT id, school_year_id AS schoolYearId, name, grade, school_type AS schoolType, students_count AS studentsCount, notes, accent, created_at AS createdAt, updated_at AS updatedAt FROM class_groups ORDER BY name COLLATE NOCASE').all() as unknown as ClassGroup[],
      assignments: this.database.prepare('SELECT id, class_group_id AS classGroupId, subject_id AS subjectId, curriculum_id AS curriculumId, school_year_id AS schoolYearId, teacher_id AS teacherId, created_at AS createdAt, updated_at AS updatedAt FROM class_subject_assignments').all() as unknown as ClassSubjectAssignment[],
      annotations: this.database.prepare('SELECT id, class_subject_assignment_id AS classSubjectAssignmentId, curriculum_node_id AS curriculumNodeId, node_kind AS nodeKind, status, planned_week AS plannedWeek, planned_start_date AS plannedStartDate, planned_end_date AS plannedEndDate, teaching_sequence_id AS teachingSequenceId, scheduled_lesson_id AS scheduledLessonId, priority, created_at AS createdAt, updated_at AS updatedAt FROM curriculum_annotations').all() as unknown as CurriculumAnnotation[],
      comments: this.database.prepare('SELECT id, class_subject_assignment_id AS classSubjectAssignmentId, curriculum_node_id AS curriculumNodeId, selected_text AS selectedText, anchor_start AS anchorStart, anchor_end AS anchorEnd, comment, resolved, created_at AS createdAt, updated_at AS updatedAt FROM curriculum_comments').all().map((row) => ({ ...(row as Omit<CurriculumComment, 'resolved'> & { resolved: number }), resolved: (row as { resolved: number }).resolved === 1 })) as CurriculumComment[],
      sequences: this.database.prepare('SELECT id, class_subject_assignment_id AS classSubjectAssignmentId, title, description, overarching_question AS overarchingQuestion, learning_goal AS learningGoal, start_date AS startDate, end_date AS endDate, status, notes, created_at AS createdAt, updated_at AS updatedAt FROM teaching_sequences').all() as unknown as TeachingSequence[],
      sequenceCurriculumReferences: this.database.prepare('SELECT id, teaching_sequence_id AS teachingSequenceId, curriculum_node_id AS curriculumNodeId, node_kind AS nodeKind, relation_type AS relationType, created_at AS createdAt, updated_at AS updatedAt FROM sequence_curriculum_references ORDER BY teaching_sequence_id').all() as unknown as SequenceCurriculumReference[],
      sequenceCompetencies: this.database.prepare('SELECT id, teaching_sequence_id AS teachingSequenceId, competency_id AS competencyId, role, created_at AS createdAt, updated_at AS updatedAt FROM sequence_competencies ORDER BY teaching_sequence_id').all() as unknown as SequenceCompetency[],
      sequenceLessons: this.database.prepare('SELECT id, teaching_sequence_id AS teachingSequenceId, position, scheduled_lesson_id AS scheduledLessonId, plan_id AS planId, planned_date AS plannedDate, planned_duration AS plannedDuration, title, guiding_question AS guidingQuestion, lesson_objective AS lessonObjective, content_summary AS contentSummary, competence_focus AS competenceFocus, curriculum_node_id AS curriculumNodeId, methods_summary AS methodsSummary, materials_summary AS materialsSummary, didactic_note AS didacticNote, status, created_at AS createdAt, updated_at AS updatedAt FROM sequence_lessons ORDER BY teaching_sequence_id, position').all().map((row) => {
        const value = row as unknown as SequenceLesson
        return { ...value, scheduledLessonId: value.scheduledLessonId ?? undefined, planId: value.planId ?? undefined, plannedDate: value.plannedDate ?? undefined, plannedDuration: value.plannedDuration ?? undefined, guidingQuestion: value.guidingQuestion ?? undefined, lessonObjective: value.lessonObjective ?? undefined, contentSummary: value.contentSummary ?? undefined, competenceFocus: value.competenceFocus ?? undefined, curriculumNodeId: value.curriculumNodeId ?? undefined, methodsSummary: value.methodsSummary ?? undefined, materialsSummary: value.materialsSummary ?? undefined, didacticNote: value.didacticNote ?? undefined }
      }) as SequenceLesson[],
      scheduledLessons: this.database.prepare('SELECT id, class_subject_assignment_id AS classSubjectAssignmentId, sequence_lesson_id AS sequenceLessonId, plan_id AS planId, date, start_time AS startTime, end_time AS endTime, status, context_type AS contextType, created_at AS createdAt, updated_at AS updatedAt FROM scheduled_lessons ORDER BY date, start_time').all() as unknown as ScheduledLesson[],
      timetableVersions: this.database.prepare('SELECT id, school_year_id AS schoolYearId, name, valid_from AS validFrom, valid_until AS validUntil, active, created_at AS createdAt, updated_at AS updatedAt FROM timetable_versions ORDER BY valid_from DESC').all().map((row) => ({ ...(row as Omit<TimetableVersion, 'active'> & { active: number }), active: (row as { active: number }).active === 1 })) as TimetableVersion[],
      timetableSlots: this.database.prepare('SELECT id, timetable_version_id AS timetableVersionId, class_subject_assignment_id AS classSubjectAssignmentId, weekday, start_time AS startTime, end_time AS endTime, room, context_type AS contextType, created_at AS createdAt, updated_at AS updatedAt FROM timetable_slots ORDER BY weekday, start_time').all() as unknown as TimetableSlot[],
      calendarExceptions: this.database.prepare('SELECT id, school_year_id AS schoolYearId, class_subject_assignment_id AS classSubjectAssignmentId, timetable_slot_id AS timetableSlotId, date, type, title, replacement_start_time AS replacementStartTime, replacement_end_time AS replacementEndTime, note, created_at AS createdAt, updated_at AS updatedAt FROM calendar_exceptions ORDER BY date').all() as unknown as CalendarException[],
      lessonReflections: this.database.prepare('SELECT id, sequence_lesson_id AS sequenceLessonId, outcome, note, repeat_needed AS repeatNeeded, created_at AS createdAt, updated_at AS updatedAt FROM lesson_reflections').all().map((row) => ({ ...(row as Omit<LessonReflection, 'repeatNeeded'> & { repeatNeeded: number }), repeatNeeded: (row as { repeatNeeded: number }).repeatNeeded === 1 })) as LessonReflection[],
      existingPlanContexts: this.database.prepare('SELECT plan_id AS planId, context_type AS contextType, created_at AS createdAt, updated_at AS updatedAt FROM existing_plan_contexts').all() as unknown as ExistingPlanContext[],
    }
  }
  saveSchoolYear(value: SchoolYear): SchoolYear { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO school_years (id,name,federal_state,school_type,start_date,end_date,school_id,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,federal_state=excluded.federal_state,school_type=excluded.school_type,start_date=excluded.start_date,end_date=excluded.end_date,school_id=excluded.school_id,active=excluded.active,updated_at=excluded.updated_at').run(value.id, value.name, value.federalState, value.schoolType, value.startDate, value.endDate, value.schoolId ?? null, value.active ? 1 : 0, createdAt, stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveClassGroup(value: ClassGroup): ClassGroup { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO class_groups (id,school_year_id,name,grade,school_type,students_count,notes,accent,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET school_year_id=excluded.school_year_id,name=excluded.name,grade=excluded.grade,school_type=excluded.school_type,students_count=excluded.students_count,notes=excluded.notes,accent=excluded.accent,updated_at=excluded.updated_at').run(value.id,value.schoolYearId,value.name,value.grade,value.schoolType,value.studentsCount ?? null,value.notes ?? null,value.accent ?? null,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveAssignment(value: ClassSubjectAssignment): ClassSubjectAssignment { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO class_subject_assignments (id,class_group_id,subject_id,curriculum_id,school_year_id,teacher_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET class_group_id=excluded.class_group_id,subject_id=excluded.subject_id,curriculum_id=excluded.curriculum_id,school_year_id=excluded.school_year_id,teacher_id=excluded.teacher_id,updated_at=excluded.updated_at').run(value.id,value.classGroupId,value.subjectId,value.curriculumId,value.schoolYearId,value.teacherId ?? null,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveAnnotation(value: CurriculumAnnotation): CurriculumAnnotation { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO curriculum_annotations (id,class_subject_assignment_id,curriculum_node_id,node_kind,status,planned_week,planned_start_date,planned_end_date,teaching_sequence_id,scheduled_lesson_id,priority,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,planned_week=excluded.planned_week,planned_start_date=excluded.planned_start_date,planned_end_date=excluded.planned_end_date,teaching_sequence_id=excluded.teaching_sequence_id,scheduled_lesson_id=excluded.scheduled_lesson_id,priority=excluded.priority,updated_at=excluded.updated_at').run(value.id,value.classSubjectAssignmentId,value.curriculumNodeId,value.nodeKind,value.status,value.plannedWeek ?? null,value.plannedStartDate ?? null,value.plannedEndDate ?? null,value.teachingSequenceId ?? null,value.scheduledLessonId ?? null,value.priority ?? null,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveSequence(value: TeachingSequence): TeachingSequence { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO teaching_sequences (id,class_subject_assignment_id,title,description,overarching_question,learning_goal,start_date,end_date,status,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,overarching_question=excluded.overarching_question,learning_goal=excluded.learning_goal,start_date=excluded.start_date,end_date=excluded.end_date,status=excluded.status,notes=excluded.notes,updated_at=excluded.updated_at').run(value.id,value.classSubjectAssignmentId,value.title,value.description ?? null,value.overarchingQuestion ?? null,value.learningGoal ?? null,value.startDate ?? null,value.endDate ?? null,value.status,value.notes ?? null,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveSequenceCurriculumReference(value: SequenceCurriculumReference): SequenceCurriculumReference { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO sequence_curriculum_references (id,teaching_sequence_id,curriculum_node_id,node_kind,relation_type,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(teaching_sequence_id,curriculum_node_id) DO UPDATE SET node_kind=excluded.node_kind,relation_type=excluded.relation_type,updated_at=excluded.updated_at').run(value.id,value.teachingSequenceId,value.curriculumNodeId,value.nodeKind,value.relationType,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveSequenceCompetency(value: SequenceCompetency): SequenceCompetency { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO sequence_competencies (id,teaching_sequence_id,competency_id,role,created_at,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(teaching_sequence_id,competency_id) DO UPDATE SET role=excluded.role,updated_at=excluded.updated_at').run(value.id,value.teachingSequenceId,value.competencyId,value.role,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveComment(value: CurriculumComment): CurriculumComment { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO curriculum_comments (id,class_subject_assignment_id,curriculum_node_id,selected_text,anchor_start,anchor_end,comment,resolved,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET selected_text=excluded.selected_text,anchor_start=excluded.anchor_start,anchor_end=excluded.anchor_end,comment=excluded.comment,resolved=excluded.resolved,updated_at=excluded.updated_at').run(value.id,value.classSubjectAssignmentId,value.curriculumNodeId,value.selectedText ?? null,value.anchorStart ?? null,value.anchorEnd ?? null,value.comment,value.resolved ? 1 : 0,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveSequenceLesson(value: SequenceLesson): SequenceLesson { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO sequence_lessons (id,teaching_sequence_id,position,scheduled_lesson_id,plan_id,planned_date,planned_duration,title,guiding_question,lesson_objective,content_summary,competence_focus,curriculum_node_id,methods_summary,materials_summary,didactic_note,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET position=excluded.position,scheduled_lesson_id=excluded.scheduled_lesson_id,plan_id=excluded.plan_id,planned_date=excluded.planned_date,planned_duration=excluded.planned_duration,title=excluded.title,guiding_question=excluded.guiding_question,lesson_objective=excluded.lesson_objective,content_summary=excluded.content_summary,competence_focus=excluded.competence_focus,curriculum_node_id=excluded.curriculum_node_id,methods_summary=excluded.methods_summary,materials_summary=excluded.materials_summary,didactic_note=excluded.didactic_note,status=excluded.status,updated_at=excluded.updated_at').run(value.id,value.teachingSequenceId,value.position,value.scheduledLessonId ?? null,value.planId ?? null,value.plannedDate ?? null,value.plannedDuration ?? null,value.title,value.guidingQuestion ?? null,value.lessonObjective ?? null,value.contentSummary ?? null,value.competenceFocus ?? null,value.curriculumNodeId ?? null,value.methodsSummary ?? null,value.materialsSummary ?? null,value.didacticNote ?? null,value.status,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveScheduledLesson(value: ScheduledLesson): ScheduledLesson { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO scheduled_lessons (id,class_subject_assignment_id,sequence_lesson_id,plan_id,date,start_time,end_time,status,context_type,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET sequence_lesson_id=excluded.sequence_lesson_id,plan_id=excluded.plan_id,date=excluded.date,start_time=excluded.start_time,end_time=excluded.end_time,status=excluded.status,context_type=excluded.context_type,updated_at=excluded.updated_at').run(value.id,value.classSubjectAssignmentId,value.sequenceLessonId ?? null,value.planId ?? null,value.date,value.startTime ?? null,value.endTime ?? null,value.status,value.contextType,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveTimetableVersion(value: TimetableVersion): TimetableVersion { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO timetable_versions (id,school_year_id,name,valid_from,valid_until,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,valid_from=excluded.valid_from,valid_until=excluded.valid_until,active=excluded.active,updated_at=excluded.updated_at').run(value.id,value.schoolYearId,value.name,value.validFrom,value.validUntil ?? null,value.active ? 1 : 0,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveTimetableSlot(value: TimetableSlot): TimetableSlot { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO timetable_slots (id,timetable_version_id,class_subject_assignment_id,weekday,start_time,end_time,room,context_type,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET timetable_version_id=excluded.timetable_version_id,class_subject_assignment_id=excluded.class_subject_assignment_id,weekday=excluded.weekday,start_time=excluded.start_time,end_time=excluded.end_time,room=excluded.room,context_type=excluded.context_type,updated_at=excluded.updated_at').run(value.id,value.timetableVersionId,value.classSubjectAssignmentId,value.weekday,value.startTime,value.endTime,value.room ?? null,value.contextType,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveCalendarException(value: CalendarException): CalendarException { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO calendar_exceptions (id,school_year_id,class_subject_assignment_id,timetable_slot_id,date,type,title,replacement_start_time,replacement_end_time,note,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET class_subject_assignment_id=excluded.class_subject_assignment_id,timetable_slot_id=excluded.timetable_slot_id,date=excluded.date,type=excluded.type,title=excluded.title,replacement_start_time=excluded.replacement_start_time,replacement_end_time=excluded.replacement_end_time,note=excluded.note,updated_at=excluded.updated_at').run(value.id,value.schoolYearId,value.classSubjectAssignmentId ?? null,value.timetableSlotId ?? null,value.date,value.type,value.title,value.replacementStartTime ?? null,value.replacementEndTime ?? null,value.note ?? null,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  saveLessonReflection(value: LessonReflection): LessonReflection { const stamp = now(); const createdAt = value.createdAt || stamp; this.database.prepare('INSERT INTO lesson_reflections (id,sequence_lesson_id,outcome,note,repeat_needed,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(sequence_lesson_id) DO UPDATE SET outcome=excluded.outcome,note=excluded.note,repeat_needed=excluded.repeat_needed,updated_at=excluded.updated_at').run(value.id,value.sequenceLessonId,value.outcome,value.note ?? null,value.repeatNeeded ? 1 : 0,createdAt,stamp); return { ...value, createdAt, updatedAt: stamp } }
  remove(table: 'school_years' | 'class_groups' | 'class_subject_assignments' | 'curriculum_annotations' | 'curriculum_comments' | 'teaching_sequences' | 'sequence_curriculum_references' | 'sequence_competencies' | 'sequence_lessons' | 'scheduled_lessons' | 'timetable_versions' | 'timetable_slots' | 'calendar_exceptions', id: string): boolean { return this.database.prepare(`DELETE FROM ${table} WHERE id = ?`).run(id).changes > 0 }
}
