import { expect, test } from '@playwright/test'
import { createPlan } from '../src/domain/factories'
import { copyFile, readFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import { PDFDocument } from 'pdf-lib'

test('übernimmt Lehrplan- und Kompetenzbezüge beim Anlegen einer Reihe', async ({ page, request }) => {
  const stamp = new Date().toISOString()
  const schoolYearId = randomUUID()
  const classGroupId = randomUUID()
  const assignmentId = randomUUID()
  await request.put(`/api/school-planning/school-years/${schoolYearId}`, { data: { id: schoolYearId, name: '2026/27', federalState: 'TH', schoolType: 'Gymnasium', startDate: '2026-08-01', endDate: '2027-07-31', active: true, createdAt: stamp, updatedAt: stamp } })
  await request.put(`/api/school-planning/class-groups/${classGroupId}`, { data: { id: classGroupId, schoolYearId, name: '8a', grade: 8, schoolType: 'Gymnasium', createdAt: stamp, updatedAt: stamp } })
  await request.put(`/api/school-planning/assignments/${assignmentId}`, { data: { id: assignmentId, classGroupId, schoolYearId, subjectId: 'subject-history', curriculumId: 'th-gym-history-2021', createdAt: stamp, updatedAt: stamp } })

  await page.goto('/lehrplan')
  await page.locator('.node-select').first().click()
  await expect(page.locator('.competency-choice')).toHaveCount(2)
  await page.getByRole('button', { name: 'Gespeicherte Reihe anlegen' }).click()
  await expect(page).toHaveURL(/\/reihen$/)
  await expect(page.locator('.reference-chip')).toContainText('Zentrale Inhalte Klassenstufen 7/8')
  await expect(page.locator('.competency-chip')).toHaveCount(2)
})

test('Mindmap bearbeiten, lokal speichern und auf dem Audience-Fenster zeigen', async ({ page, request, context }) => {
  const plan = createPlan('Mindmap Browserprüfung')
  await request.put(`/api/plans/${plan.id}`, { data: plan })
  await page.goto(`/plan/${plan.id}/presentation`)
  await expect(page.getByTitle('Mindmap')).toBeVisible()
  await page.getByTitle('Mindmap').click()
  await expect(page.locator('.map-node input')).toBeVisible()
  await page.locator('.map-node input').fill('Fotosynthese')
  await page.locator('.map-node input').press('Enter')
  await page.getByRole('button', { name: '+ Unterast' }).click()
  await page.locator('.map-node input').fill('Voraussetzungen')
  await page.locator('.map-node input').press('Enter')
  await page.getByRole('button', { name: '+ Geschwister' }).click()
  await page.locator('.map-node input').fill('Produkte')
  await page.locator('.map-node input').press('Enter')
  const mapNodePositions = await page.locator('.map-node').evaluateAll((nodes) => nodes.map((node) => ({
    root: node.classList.contains('root'),
    left: Number.parseFloat((node as HTMLElement).style.left),
  })))
  const rootPosition = mapNodePositions.find((node) => node.root)?.left ?? 50
  const branchPositions = mapNodePositions.filter((node) => !node.root).map((node) => node.left)
  expect(branchPositions.some((left) => left < rootPosition)).toBe(true)
  expect(branchPositions.some((left) => left > rootPosition)).toBe(true)
  await page.locator('.map-toolbar').getByRole('button', { name: '+', exact: true }).click()
  await expect(page.locator('.map-toolbar small')).toHaveText('110%')
  await page.getByRole('button', { name: 'Zentrieren' }).click()
  await expect(page.locator('.map-toolbar small')).toHaveText('100%')
  await page.getByRole('button', { name: 'Bearbeitung beenden' }).last().click()
  await page.getByRole('button', { name: '+ Folie' }).click()
  await page.locator('.thumb').first().click()
  await expect(page.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen', 'Produkte'])
  await expect.poll(async () => {
    const response = await request.get(`/api/plans/${plan.id}`)
    const saved = await response.json()
    return saved.presentation?.slides?.[0]?.elements?.[0]?.content?.mindmap?.nodes?.length
  }).toBe(3)
  await page.reload()
  await expect(page.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen', 'Produkte'])
  const popupPromise = context.waitForEvent('page')
  await page.getByRole('button', { name: 'Präsentieren' }).click()
  const audience = await popupPromise
  await expect(page.getByText('Presenter Console')).toBeVisible()
  await expect(page.locator('.speaker-notes')).toBeVisible()
  await expect(page.getByRole('toolbar', { name: 'Folienvorschau skalieren' })).toBeVisible()
  await expect(page.locator('.presenter-slide-stage .slide-design')).toHaveCSS('width', '1280px')
  await expect(page.locator('.presenter-slide-stage .slide-design')).toHaveCSS('height', '720px')
  await expect(audience.locator('.slide-design')).toHaveCSS('width', '1280px')
  await expect(audience.locator('.slide-design')).toHaveCSS('height', '720px')
  const presenterHeight = await page.evaluate(() => ({ client: document.documentElement.clientHeight, scroll: document.documentElement.scrollHeight }))
  expect(presenterHeight.scroll).toBeLessThanOrEqual(presenterHeight.client)
  const presenterStageBeforeScale = await page.locator('.presenter-slide-stage').boundingBox()
  await page.getByRole('button', { name: 'Folienvorschau verkleinern' }).click()
  const presenterStageAfterScale = await page.locator('.presenter-slide-stage').boundingBox()
  if (!presenterStageBeforeScale || !presenterStageAfterScale) throw new Error('Referenten-Folienvorschau ist nicht sichtbar')
  expect(presenterStageAfterScale.width).toBeLessThan(presenterStageBeforeScale.width)
  await expect(audience.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen', 'Produkte'])
  await page.getByRole('button', { name: 'Mindmap bearbeiten' }).click()
  await expect(page.locator('.live-mindmap-panel .map-toolbar')).toBeVisible()
  await page.locator('.live-mindmap-panel').getByRole('button', { name: '+ Unterast' }).click()
  await page.locator('.live-mindmap-panel .map-node input').fill('Chlorophyll')
  await page.locator('.live-mindmap-panel .map-node input').press('Enter')
  await expect(audience.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen', 'Produkte', 'Chlorophyll'])
  await page.getByRole('button', { name: 'Zur Folienvorschau' }).click()
  await page.getByRole('button', { name: 'Referentenansicht vergrößern' }).click()
  await page.getByRole('button', { name: 'Zoom im Plenum einschalten' }).click()
  await expect(audience.locator('.slide-content')).toHaveAttribute('style', /scale\(1\.25\)/)
  await page.locator('.presenter-slide-stage').hover()
  await page.mouse.wheel(0, -120)
  await expect(audience.locator('.slide-content')).toHaveAttribute('style', /scale\(1\.42\)/)
  await audience.locator('.audience-stage').hover()
  await audience.mouse.wheel(0, 120)
  await expect(page.locator('.presenter-slide-stage .slide-content')).toHaveAttribute('style', /scale\(1\.25\)/)
  await expect(page.getByRole('button', { name: 'Bildausschnitt nach links bewegen' })).toHaveCount(0)
  const panStage = await page.locator('.presenter-slide-stage').boundingBox()
  if (!panStage) throw new Error('Presenter-Folienfläche ist nicht sichtbar')
  await page.mouse.move(panStage.x + panStage.width * .45, panStage.y + panStage.height * .45)
  await page.mouse.down({ button: 'right' })
  await page.mouse.move(panStage.x + panStage.width * .67, panStage.y + panStage.height * .58, { steps: 8 })
  await page.mouse.up({ button: 'right' })
  await expect.poll(() => audience.locator('.slide-content').getAttribute('style')).not.toContain('translate(0%, 0%)')
  const presenterPanBeforeAudienceMove = await page.locator('.presenter-slide-stage .slide-content').getAttribute('style')
  const audiencePanStage = await audience.locator('.audience-stage').boundingBox()
  if (!audiencePanStage) throw new Error('Präsentationsfenster ist nicht sichtbar')
  await audience.mouse.move(audiencePanStage.x + audiencePanStage.width * .58, audiencePanStage.y + audiencePanStage.height * .55)
  await audience.mouse.down({ button: 'right' })
  await audience.mouse.move(audiencePanStage.x + audiencePanStage.width * .37, audiencePanStage.y + audiencePanStage.height * .43, { steps: 8 })
  await audience.mouse.up({ button: 'right' })
  await expect.poll(() => page.locator('.presenter-slide-stage .slide-content').getAttribute('style')).not.toBe(presenterPanBeforeAudienceMove)
  await page.getByRole('button', { name: 'Stift', exact: true }).click()
  const stage = await page.locator('.presenter-slide-stage').boundingBox()
  if (!stage) throw new Error('Presenter-Folienfläche ist nicht sichtbar')
  await page.mouse.move(stage.x + stage.width * 0.3, stage.y + stage.height * 0.35)
  await page.mouse.down()
  await page.mouse.move(stage.x + stage.width * 0.55, stage.y + stage.height * 0.45, { steps: 5 })
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBeGreaterThan(0)
  await page.mouse.up()
  console.log('Presenter ink paths:', await page.locator('.presentation-ink-overlay path').evaluateAll((paths) => paths.map((path) => path.getAttribute('d'))))
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Leuchtstift' }).click()
  await page.getByLabel('Leuchtdauer in Sekunden').fill('1')
  await page.mouse.move(stage.x + stage.width * 0.35, stage.y + stage.height * 0.55)
  await page.mouse.down()
  await page.mouse.move(stage.x + stage.width * 0.6, stage.y + stage.height * 0.6, { steps: 5 })
  await page.mouse.up()
  await expect.poll(() => audience.locator('.presentation-ink-glow-segment').count()).toBeGreaterThan(0)
  await expect(audience.locator('.presentation-ink-overlay path')).toHaveCount(1, { timeout: 3000 })
  await page.getByRole('button', { name: 'Zoom im Plenum ausschalten' }).click()
  await expect(audience.locator('.slide-content')).toHaveAttribute('style', /scale\(1\)/)
  await expect.poll(async () => {
    const response = await request.get(`/api/plans/${plan.id}`)
    const saved = await response.json()
    return saved.presentation?.slides?.[0]?.elements?.[0]?.content?.mindmap?.nodes?.length
  }).toBe(4)
  await page.getByRole('button', { name: 'Nächste →' }).click()
  await expect(audience.getByText('Titel hinzufügen')).toBeVisible()
  await expect(audience.locator('.map-node')).toHaveCount(0)
  await page.getByRole('button', { name: '← Vorherige' }).click()
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBe(1)
  await page.getByRole('button', { name: 'Präsentationsfenster zeichnen: aus' }).click()
  await audience.getByRole('button', { name: 'Stift', exact: true }).click()
  const audienceStage = await audience.locator('.audience-stage').boundingBox()
  if (!audienceStage) throw new Error('Präsentationsfenster ist nicht sichtbar')
  await audience.mouse.move(audienceStage.x + audienceStage.width * 0.35, audienceStage.y + audienceStage.height * 0.3)
  await audience.mouse.down()
  await audience.mouse.move(audienceStage.x + audienceStage.width * 0.6, audienceStage.y + audienceStage.height * 0.4, { steps: 5 })
  await expect.poll(() => page.locator('.presentation-ink-overlay path').count()).toBe(2)
  await audience.mouse.up()
  await expect.poll(() => page.locator('.presentation-ink-overlay path').count()).toBe(2)
  await page.getByRole('button', { name: 'Zeichnungen dieser Folie löschen' }).click()
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBe(0)
  await page.getByRole('button', { name: 'Präsentation beenden' }).click()
  await expect(audience.getByText('Präsentation beendet.')).toBeVisible()
})

test('erstellt einen Zeitstrahl, bearbeitet Ereignisse und zeigt ihn im Präsentationsfenster', async ({ page, request, context }) => {
  const plan = createPlan('Zeitstrahl Browserprüfung')
  await request.put(`/api/plans/${plan.id}`, { data: plan })
  await page.goto(`/plan/${plan.id}/presentation`)

  await page.getByTitle('Zeitstrahl').click()
  await expect(page.locator('.timeline-widget')).toBeVisible()
  await expect(page.locator('.timeline-edit-card')).toHaveCount(3)
  await page.locator('.timeline-tools').getByRole('button', { name: '+ Ereignis' }).click()
  await expect(page.locator('.timeline-edit-card')).toHaveCount(4)
  await page.locator('.timeline-title').nth(1).fill('Auftakt')
  await page.locator('.timeline-title').nth(1).press('Enter')
  await page.locator('.timeline-tools').getByRole('button', { name: 'Bearbeitung beenden' }).click()

  await expect.poll(async () => {
    const response = await request.get(`/api/plans/${plan.id}`)
    const saved = await response.json()
    return saved.presentation?.slides?.[0]?.elements?.[0]?.content?.timeline?.entries?.map((entry: { title: string }) => entry.title)
  }).toContain('Auftakt')
  await page.reload()
  await expect(page.locator('.timeline-widget')).toContainText('Auftakt')

  const popupPromise = context.waitForEvent('page')
  await page.getByRole('button', { name: 'Präsentieren' }).click()
  const audience = await popupPromise
  await expect(audience.locator('.timeline-widget')).toContainText('Auftakt')
  await page.getByRole('button', { name: 'Zeitstrahl bearbeiten' }).click()
  await expect(page.locator('.live-timeline-panel')).toBeVisible()
  await page.locator('.live-timeline-panel .timeline-date').first().fill('476 v. Chr.')
  await expect(audience.locator('.timeline-widget')).toContainText('476 v. Chr.')
  await page.locator('.live-timeline-panel .timeline-tools').getByRole('button', { name: '+ Ereignis' }).click()
  await expect(audience.locator('.timeline-entry')).toHaveCount(5)
})

test('speichert lokale Bild- und Videokopien in SQLite und akzeptiert externe Medien-URLs', async ({ page, request }) => {
  const plan = createPlan('Medien Browserprüfung')
  await request.put(`/api/plans/${plan.id}`, { data: plan })
  await page.goto(`/plan/${plan.id}/presentation`)

  await page.getByTitle('Bild').click()
  await page.getByPlaceholder('Bild-URL (https://…)').fill('https://example.test/wald.jpg')
  await page.getByRole('button', { name: 'URL einfügen' }).click()
  await expect(page.locator('.slide-element.image img')).toHaveAttribute('src', 'https://example.test/wald.jpg')
  await page.getByTitle('Bild').click()
  await page.locator('.toolbar .image-picker').getByLabel('Bilddatei als Kopie auswählen').setInputFiles({ name: 'wald.png', mimeType: 'image/png', buffer: Buffer.from([137, 80, 78, 71]) })
  await expect(page.locator('.slide-element.image img')).toHaveCount(2)
  const copiedImage = await page.locator('.slide-element.image img').last().getAttribute('src')
  expect(copiedImage).toMatch(/^\/api\/presentation-media\//)
  const copiedImageResponse = await request.get(copiedImage!)
  expect(copiedImageResponse.headers()['content-type']).toBe('image/png')
  expect(await copiedImageResponse.body()).toEqual(Buffer.from([137, 80, 78, 71]))

  await page.getByTitle('Video').click()
  await page.getByPlaceholder('Video-URL (https://…)').fill('https://example.test/erklaerung.mp4')
  await page.getByRole('button', { name: 'URL einfügen' }).click()
  await expect(page.locator('.slide-element.video video')).toHaveAttribute('src', 'https://example.test/erklaerung.mp4')
  await page.getByTitle('Video').click()
  await page.locator('.toolbar .image-picker').getByLabel('Videodatei als Kopie auswählen').setInputFiles({ name: 'erklaerung.mp4', mimeType: 'video/mp4', buffer: Buffer.from([0, 0, 0, 24]) })
  await expect(page.locator('.slide-element.video video')).toHaveCount(2)
  const copiedVideo = await page.locator('.slide-element.video video').last().getAttribute('src')
  expect(copiedVideo).toMatch(/^\/api\/presentation-media\//)
  expect((await request.get(copiedVideo!)).headers()['content-type']).toBe('video/mp4')
  await expect.poll(async () => (await (await request.get(`/api/plans/${plan.id}`)).json()).presentation.slides[0].elements.map((element: { type: string; content: { src?: string } }) => ({ type: element.type, src: element.content.src }))).toEqual(expect.arrayContaining([{ type: 'image', src: 'https://example.test/wald.jpg' }, { type: 'video', src: 'https://example.test/erklaerung.mp4' }, { type: 'image', src: copiedImage }, { type: 'video', src: copiedVideo }]))
})

test('sammelt Abstimmungs-Klicks im Plenum und zeigt das Ergebnis erst nach Freigabe', async ({ page, request, context }) => {
  const plan = createPlan('Abstimmung Browserprüfung')
  await request.put(`/api/plans/${plan.id}`, { data: plan })
  await page.goto(`/plan/${plan.id}/presentation`)
  await page.getByTitle('Abstimmung').click()
  await page.getByRole('button', { name: 'Bearbeitung beenden' }).click()
  await expect.poll(async () => (await (await request.get(`/api/plans/${plan.id}`)).json()).presentation?.slides?.[0]?.elements?.[0]?.type).toBe('poll')

  const popupPromise = context.waitForEvent('page')
  await page.getByRole('button', { name: 'Präsentieren' }).click()
  const audience = await popupPromise
  await audience.getByRole('button', { name: 'Ja' }).click()
  await expect(page.locator('.presenter-poll-preview')).toContainText('1 Stimme')
  await expect(page.locator('.presenter-poll-preview .presenter-poll-bar').first()).toContainText('1 Stimme · 100 %')
  await expect(page.locator('.presenter-poll-preview .presenter-poll-bar-track i').first()).toHaveAttribute('style', /width: 100%/)
  await expect(audience.locator('.vote-total')).toHaveCount(0)
  await page.getByRole('button', { name: 'Ergebnis anzeigen' }).click()
  await expect(audience.locator('.vote-total')).toHaveText('1 Stimme')
  await expect(audience.locator('.poll-result').first()).toContainText('100 %')
})

test('exportiert alle Folien als selbstständiges HTML und als PDF', async ({ page, request, context }) => {
  test.setTimeout(60_000)
  const plan = createPlan('Export Browserprüfung')
  await request.put(`/api/plans/${plan.id}`, { data: plan })
  await page.goto(`/plan/${plan.id}/presentation`)
  await page.getByTitle('Mindmap').click()
  await page.locator('.map-node input').fill('Fotosynthese')
  await page.locator('.map-node input').press('Enter')
  await page.getByRole('button', { name: 'Bearbeitung beenden' }).last().click()
  await page.getByRole('button', { name: '+ Folie' }).click()

  const htmlDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'HTML exportieren' }).click()
  const htmlFile = await htmlDownload
  expect(htmlFile.suggestedFilename()).toMatch(/\.html$/)
  const html = await readFile(await htmlFile.path(), 'utf8')
  expect(html).toContain('data:image/png;base64,')
  const htmlPage = await context.newPage()
  await htmlPage.setContent(html)
  await expect(htmlPage.getByText('Folie 1 / 2')).toBeVisible()
  await htmlPage.getByRole('button', { name: 'Nächste Folie' }).click()
  await expect(htmlPage.getByText('Folie 2 / 2')).toBeVisible()
  await htmlPage.close()

  const pdfDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'PDF exportieren' }).click()
  const pdfFile = await pdfDownload
  expect(pdfFile.suggestedFilename()).toMatch(/\.pdf$/)
  const pdfPath = await pdfFile.path()
  const pdf = await PDFDocument.load(await readFile(pdfPath))
  expect(pdf.getPageCount()).toBe(2)
  expect(pdf.getPage(0).getSize()).toMatchObject({ width: 960, height: 540 })
  await copyFile(pdfPath, 'test-results/presentation-export.pdf')
})
