import { expect, test } from '@playwright/test'
import { createPlan } from '../src/domain/factories'
import { copyFile, readFile } from 'node:fs/promises'
import { PDFDocument } from 'pdf-lib'

test('Mindmap bearbeiten, lokal speichern und auf dem Audience-Fenster zeigen', async ({ page, request, context }) => {
  const plan = createPlan('Mindmap Browserprüfung')
  await request.put(`/api/plans/${plan.id}`, { data: plan })
  await page.goto(`/plan/${plan.id}/presentation`)
  await expect(page.getByTitle('Mindmap')).toBeVisible()
  await page.getByTitle('Mindmap').click()
  await expect(page.locator('.map-node input')).toBeVisible()
  await page.locator('.map-node input').fill('Fotosynthese')
  await page.locator('.map-node input').press('Enter')
  await page.getByRole('button', { name: '+ Unterast' }).click()
  await page.locator('.map-node input').fill('Voraussetzungen')
  await page.locator('.map-node input').press('Enter')
  await page.locator('.map-toolbar').getByRole('button', { name: '+', exact: true }).click()
  await expect(page.locator('.map-toolbar small')).toHaveText('110%')
  await page.getByRole('button', { name: 'Zentrieren' }).click()
  await expect(page.locator('.map-toolbar small')).toHaveText('100%')
  await page.getByRole('button', { name: 'Bearbeitung beenden' }).last().click()
  await page.getByRole('button', { name: '+ Folie' }).click()
  await page.locator('.thumb').first().click()
  await expect(page.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen'])
  await expect.poll(async () => {
    const response = await request.get(`/api/plans/${plan.id}`)
    const saved = await response.json()
    return saved.presentation?.slides?.[0]?.elements?.[0]?.content?.mindmap?.nodes?.length
  }).toBe(2)
  await page.reload()
  await expect(page.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen'])
  const popupPromise = context.waitForEvent('page')
  await page.getByRole('button', { name: 'Präsentieren' }).click()
  const audience = await popupPromise
  await expect(page.getByText('Presenter Console')).toBeVisible()
  await expect(page.locator('.speaker-notes')).toBeVisible()
  await expect(page.getByRole('toolbar', { name: 'Folienvorschau skalieren' })).toBeVisible()
  const presenterHeight = await page.evaluate(() => ({ client: document.documentElement.clientHeight, scroll: document.documentElement.scrollHeight }))
  expect(presenterHeight.scroll).toBeLessThanOrEqual(presenterHeight.client)
  const presenterStageBeforeScale = await page.locator('.presenter-slide-stage').boundingBox()
  await page.getByRole('button', { name: 'Folienvorschau verkleinern' }).click()
  const presenterStageAfterScale = await page.locator('.presenter-slide-stage').boundingBox()
  if (!presenterStageBeforeScale || !presenterStageAfterScale) throw new Error('Referenten-Folienvorschau ist nicht sichtbar')
  expect(presenterStageAfterScale.width).toBeLessThan(presenterStageBeforeScale.width)
  await expect(audience.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen'])
  await page.getByRole('button', { name: 'Mindmap bearbeiten' }).click()
  await expect(page.locator('.live-mindmap-panel .map-toolbar')).toBeVisible()
  await page.locator('.live-mindmap-panel').getByRole('button', { name: '+ Unterast' }).click()
  await page.locator('.live-mindmap-panel .map-node input').fill('Chlorophyll')
  await page.locator('.live-mindmap-panel .map-node input').press('Enter')
  await expect(audience.locator('.map-node')).toContainText(['Fotosynthese', 'Voraussetzungen', 'Chlorophyll'])
  await page.getByRole('button', { name: 'Zur Folienvorschau' }).click()
  await page.getByRole('button', { name: 'Referentenansicht vergrößern' }).click()
  await page.getByRole('button', { name: 'Zoom im Plenum einschalten' }).click()
  await expect(audience.locator('.slide-content')).toHaveAttribute('style', /scale\(1\.25\)/)
  await page.getByRole('button', { name: 'Stift', exact: true }).click()
  const stage = await page.locator('.presenter-slide-stage').boundingBox()
  if (!stage) throw new Error('Presenter-Folienfläche ist nicht sichtbar')
  await page.mouse.move(stage.x + stage.width * 0.3, stage.y + stage.height * 0.35)
  await page.mouse.down()
  await page.mouse.move(stage.x + stage.width * 0.55, stage.y + stage.height * 0.45, { steps: 5 })
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBeGreaterThan(0)
  await page.mouse.up()
  console.log('Presenter ink paths:', await page.locator('.presentation-ink-overlay path').evaluateAll((paths) => paths.map((path) => path.getAttribute('d'))))
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Leuchtstift' }).click()
  await page.getByLabel('Leuchtdauer in Sekunden').fill('1')
  await page.mouse.move(stage.x + stage.width * 0.35, stage.y + stage.height * 0.55)
  await page.mouse.down()
  await page.mouse.move(stage.x + stage.width * 0.6, stage.y + stage.height * 0.6, { steps: 5 })
  await page.mouse.up()
  await expect.poll(() => audience.locator('.presentation-ink-glow-segment').count()).toBeGreaterThan(0)
  await expect(audience.locator('.presentation-ink-overlay path')).toHaveCount(1, { timeout: 3000 })
  await page.getByRole('button', { name: 'Zoom im Plenum ausschalten' }).click()
  await expect(audience.locator('.slide-content')).toHaveAttribute('style', /scale\(1\)/)
  await expect.poll(async () => {
    const response = await request.get(`/api/plans/${plan.id}`)
    const saved = await response.json()
    return saved.presentation?.slides?.[0]?.elements?.[0]?.content?.mindmap?.nodes?.length
  }).toBe(3)
  await page.getByRole('button', { name: 'Nächste →' }).click()
  await expect(audience.getByText('Titel hinzufügen')).toBeVisible()
  await expect(audience.locator('.map-node')).toHaveCount(0)
  await page.getByRole('button', { name: '← Vorherige' }).click()
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBe(1)
  await page.getByRole('button', { name: 'Präsentationsfenster zeichnen: aus' }).click()
  await audience.getByRole('button', { name: 'Stift', exact: true }).click()
  const audienceStage = await audience.locator('.audience-stage').boundingBox()
  if (!audienceStage) throw new Error('Präsentationsfenster ist nicht sichtbar')
  await audience.mouse.move(audienceStage.x + audienceStage.width * 0.35, audienceStage.y + audienceStage.height * 0.3)
  await audience.mouse.down()
  await audience.mouse.move(audienceStage.x + audienceStage.width * 0.6, audienceStage.y + audienceStage.height * 0.4, { steps: 5 })
  await expect.poll(() => page.locator('.presentation-ink-overlay path').count()).toBe(2)
  await audience.mouse.up()
  await expect.poll(() => page.locator('.presentation-ink-overlay path').count()).toBe(2)
  await page.getByRole('button', { name: 'Zeichnungen dieser Folie löschen' }).click()
  await expect.poll(() => audience.locator('.presentation-ink-overlay path').count()).toBe(0)
  await page.getByRole('button', { name: 'Präsentation beenden' }).click()
  await expect(audience.getByText('Präsentation beendet.')).toBeVisible()
})

test('exportiert alle Folien als selbstständiges HTML und als PDF', async ({ page, request, context }) => {
  test.setTimeout(60_000)
  const plan = createPlan('Export Browserprüfung')
  await request.put(`/api/plans/${plan.id}`, { data: plan })
  await page.goto(`/plan/${plan.id}/presentation`)
  await page.getByTitle('Mindmap').click()
  await page.locator('.map-node input').fill('Fotosynthese')
  await page.locator('.map-node input').press('Enter')
  await page.getByRole('button', { name: 'Bearbeitung beenden' }).last().click()
  await page.getByRole('button', { name: '+ Folie' }).click()

  const htmlDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'HTML exportieren' }).click()
  const htmlFile = await htmlDownload
  expect(htmlFile.suggestedFilename()).toMatch(/\.html$/)
  const html = await readFile(await htmlFile.path(), 'utf8')
  expect(html).toContain('data:image/png;base64,')
  const htmlPage = await context.newPage()
  await htmlPage.setContent(html)
  await expect(htmlPage.getByText('Folie 1 / 2')).toBeVisible()
  await htmlPage.getByRole('button', { name: 'Nächste Folie' }).click()
  await expect(htmlPage.getByText('Folie 2 / 2')).toBeVisible()
  await htmlPage.close()

  const pdfDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'PDF exportieren' }).click()
  const pdfFile = await pdfDownload
  expect(pdfFile.suggestedFilename()).toMatch(/\.pdf$/)
  const pdfPath = await pdfFile.path()
  const pdf = await PDFDocument.load(await readFile(pdfPath))
  expect(pdf.getPageCount()).toBe(2)
  expect(pdf.getPage(0).getSize()).toMatchObject({ width: 960, height: 540 })
  await copyFile(pdfPath, 'test-results/presentation-export.pdf')
})
