<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getApplicableCurriculum, getCurriculum, getCurriculumTree } from '../data/curricula/registry'
import { createId } from '../domain/factories'
import type { ClassGroup, ClassSubjectAssignment, SchoolPlanningSnapshot, SchoolYear } from '../domain/schoolPlanning'
import { SchoolPlanningRepository } from '../repositories/SchoolPlanningRepository'

const router = useRouter(); const repository = new SchoolPlanningRepository()
const snapshot = ref<SchoolPlanningSnapshot>(); const error = ref(''); const notice = ref('')
const schoolYearName = ref('2026/27'); const startDate = ref('2026-08-01'); const endDate = ref('2027-07-31')
const className = ref('8a'); const classGrade = ref(8); const subjectId = ref('subject-history')
const activeYear = computed(() => snapshot.value?.schoolYears.find((year) => year.active) ?? snapshot.value?.schoolYears[0])
const classes = computed(() => snapshot.value?.classGroups.filter((group) => group.schoolYearId === activeYear.value?.id) ?? [])
const availableCurriculum = computed(() => getApplicableCurriculum({ state: 'TH', schoolType: 'gymnasium', subjectId: subjectId.value, grade: classGrade.value, schoolYear: schoolYearName.value }))
const subjects = [{ id: 'subject-history', label: 'Geschichte' }, { id: 'subject-informatics', label: 'Informatik' }, { id: 'subject-media-informatics', label: 'Medienbildung und Informatik' }]
async function load(): Promise<void> { try { snapshot.value = await repository.get() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Daten konnten nicht geladen werden.' } }
async function createSchoolYear(): Promise<void> { error.value = ''; const timestamp = new Date().toISOString(); const value: SchoolYear = { id: createId(), name: schoolYearName.value, federalState: 'TH', schoolType: 'Gymnasium', startDate: startDate.value, endDate: endDate.value, active: true, createdAt: timestamp, updatedAt: timestamp }; try { for (const year of snapshot.value?.schoolYears ?? []) if (year.active) await repository.saveSchoolYear({ ...year, active: false }); await repository.saveSchoolYear(value); notice.value = `Schuljahr ${value.name} ist aktiv.`; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Schuljahr konnte nicht gespeichert werden.' } }
async function createClass(): Promise<void> { const year = activeYear.value; if (!year) { error.value = 'Bitte zuerst ein Schuljahr anlegen.'; return } const timestamp = new Date().toISOString(); const group: ClassGroup = { id: createId(), schoolYearId: year.id, name: className.value, grade: classGrade.value, schoolType: year.schoolType, createdAt: timestamp, updatedAt: timestamp }; try { await repository.saveClassGroup(group); notice.value = `Klasse ${group.name} angelegt.`; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Klasse konnte nicht gespeichert werden.' } }
async function assign(group: ClassGroup): Promise<void> { const curriculum = availableCurriculum.value; if (!curriculum) { error.value = 'Für diese Kombination ist kein verifiziertes Curriculum verfügbar.'; return } const timestamp = new Date().toISOString(); const assignment: ClassSubjectAssignment = { id: createId(), classGroupId: group.id, schoolYearId: group.schoolYearId, subjectId: subjectId.value, curriculumId: curriculum.id, createdAt: timestamp, updatedAt: timestamp }; try { await repository.saveAssignment(assignment); notice.value = `${subjects.find((subject) => subject.id === subjectId.value)?.label} ist ${group.name} zugeordnet.`; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Zuordnung konnte nicht gespeichert werden.' } }
const assignmentsFor = (group: ClassGroup) => snapshot.value?.assignments.filter((assignment) => assignment.classGroupId === group.id) ?? []
function coverageFor(assignment: ClassSubjectAssignment): { completed: number; total: number; percent: number } {
  const group = snapshot.value?.classGroups.find((item) => item.id === assignment.classGroupId)
  const curriculum = getCurriculum(assignment.curriculumId)
  const nodeIds = curriculum ? getCurriculumTree(curriculum.id, group?.grade).flatMap((area) => area.contentPoints.map((point) => point.id)) : []
  const completed = (snapshot.value?.annotations ?? []).filter((item) => item.classSubjectAssignmentId === assignment.id && item.status === 'completed' && nodeIds.includes(item.curriculumNodeId)).length
  return { completed, total: nodeIds.length, percent: nodeIds.length ? Math.round((completed / nodeIds.length) * 100) : 0 }
}
onMounted(() => void load())
</script>

<template>
  <main class="school-planning-shell">
    <header class="school-planning-header"><div><p class="eyebrow">Unterrichtsplanung</p><h1>Schuljahr &amp; Fachlehrpläne</h1><p>Klassenbezogene Planung beginnt mit einem aktiven Schuljahr, einer Klasse und einem verifizierten Fachlehrplan.</p></div><nav><button type="button" class="secondary" @click="router.push({ name: 'timetable-settings' })">Stundenplan</button><button type="button" class="secondary" @click="router.push({ name: 'home' })">← Dashboard</button></nav></header>
    <p v-if="error" class="error-message">{{ error }}</p><p v-if="notice" class="success-message">{{ notice }}</p>
    <section class="planning-grid">
      <article class="planning-card"><p class="step">01</p><h2>Schuljahr</h2><form @submit.prevent="createSchoolYear"><label>Bezeichnung<input v-model="schoolYearName" required placeholder="2026/27"></label><div class="two"><label>Beginn<input v-model="startDate" type="date" required></label><label>Ende<input v-model="endDate" type="date" required></label></div><button type="submit">Schuljahr aktivieren</button></form><p v-if="activeYear" class="current"><strong>{{ activeYear.name }}</strong><span>Thüringen · {{ activeYear.schoolType }}</span></p></article>
      <article class="planning-card"><p class="step">02</p><h2>Klasse oder Kurs</h2><form @submit.prevent="createClass"><label>Name<input v-model="className" required placeholder="z. B. 8a"></label><label>Klassenstufe<input v-model.number="classGrade" min="1" max="13" type="number" required></label><button type="submit" :disabled="!activeYear">Klasse anlegen</button></form><p v-if="!classes.length" class="empty-state">Noch keine Klasse im aktiven Schuljahr.</p><div v-else class="class-pills"><span v-for="group in classes" :key="group.id">{{ group.name }} · {{ group.grade }}</span></div></article>
      <article class="planning-card curriculum-card"><p class="step">03</p><h2>Fachlehrplan</h2><label>Fach<select v-model="subjectId"><option v-for="subject in subjects" :key="subject.id" :value="subject.id">{{ subject.label }}</option></select></label><p v-if="availableCurriculum" class="curriculum-available"><strong>Verifiziert verfügbar</strong><span>{{ availableCurriculum.title }} · {{ availableCurriculum.version }}</span></p><p v-else class="curriculum-missing">Für Fach und Klassenstufe liegt kein verifiziertes Referenzcurriculum vor. Es wird nichts erfunden oder zugeordnet.</p></article>
    </section>
    <section class="class-overview"><header><div><p class="eyebrow">Klassenfachbereiche</p><h2>Planungsräume</h2></div><span>{{ classes.length }} Klasse{{ classes.length === 1 ? '' : 'n' }}</span></header><p v-if="!classes.length" class="empty-state">Lege oben zuerst ein Schuljahr und mindestens eine Klasse an.</p><article v-for="group in classes" :key="group.id" class="class-row"><div class="class-badge">{{ group.name }}</div><div><strong>Klassenstufe {{ group.grade }}</strong><p>{{ assignmentsFor(group).length ? assignmentsFor(group).map((assignment) => subjects.find((subject) => subject.id === assignment.subjectId)?.label).join(' · ') : 'Noch kein Fach zugeordnet' }}</p><div v-for="assignment in assignmentsFor(group)" :key="assignment.id" class="coverage" :aria-label="`Lehrplanabdeckung ${subjects.find((subject) => subject.id === assignment.subjectId)?.label}: ${coverageFor(assignment).percent} Prozent`"><span>{{ subjects.find((subject) => subject.id === assignment.subjectId)?.label }} · Lehrplanabdeckung</span><div class="coverage-bar"><span :style="{ width: `${coverageFor(assignment).percent}%` }"></span></div><strong>{{ coverageFor(assignment).percent }} %</strong><small>{{ coverageFor(assignment).completed }} von {{ coverageFor(assignment).total }} Inhalten dokumentiert behandelt</small></div></div><button v-if="availableCurriculum" type="button" @click="assign(group)">+ {{ subjects.find((subject) => subject.id === subjectId)?.label }} zuordnen</button><span v-else class="unavailable">Curriculum nicht verfügbar</span></article></section>
  </main>
</template>

<style scoped>
.school-planning-shell { max-width:1180px; margin:auto; padding:clamp(1.25rem,4vw,3.5rem); }.school-planning-header,.class-overview>header { display:flex; justify-content:space-between; gap:1rem; align-items:flex-start; }.school-planning-header nav{display:flex;gap:.5rem}.school-planning-header { padding-bottom:1.6rem; border-bottom:1px solid #cbd9db; }.school-planning-header p:last-child { max-width:48rem; color:#5b6e73; }.planning-grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:1rem; margin:1.5rem 0; }.planning-card,.class-overview { border:1px solid #cbd9db; border-radius:12px; padding:1.2rem; background:#fff; box-shadow:0 2px 12px #1833380d; }.planning-card h2 { margin-bottom:1rem; }.planning-card form { display:grid; gap:.75rem; }.two { display:grid; grid-template-columns:1fr 1fr; gap:.6rem; }.step { color:#198089; font-size:.72rem; font-weight:900; letter-spacing:.1em; }.current,.curriculum-available { display:grid; gap:.2rem; margin:1rem 0 0; padding:.7rem; border-radius:7px; color:#195b48; background:#e8f5ee; font-size:.84rem; }.curriculum-missing { margin:1rem 0 0; color:#7d5421; font-size:.85rem; line-height:1.45; }.class-pills { display:flex; flex-wrap:wrap; gap:.4rem; margin-top:1rem; }.class-pills span { padding:.3rem .55rem; color:#1c5e65; background:#e7f2f2; border-radius:999px; font-size:.8rem; font-weight:700; }.class-overview { margin-top:1rem; }.class-overview>header { align-items:center; margin-bottom:1rem; }.class-overview>header span { color:#61757a; font-size:.85rem; }.class-row { display:grid; grid-template-columns:auto 1fr auto; gap:1rem; align-items:center; padding:1rem 0; border-top:1px solid #e1e9ea; }.class-row p { margin:.2rem 0 0; color:#607379; font-size:.86rem; }.class-badge { display:grid; width:3.1rem; height:3.1rem; place-items:center; color:#fff; background:#1d777f; border-radius:10px; font-weight:900; }.unavailable { color:#7d5421; font-size:.8rem; font-weight:700; }.success-message { color:#176341; font-weight:700; }@media(max-width:800px){.planning-grid{grid-template-columns:1fr}.school-planning-header,.class-overview>header{flex-direction:column}.class-row{grid-template-columns:auto 1fr}.class-row button,.unavailable{grid-column:1/-1}.two{grid-template-columns:1fr}}
</style>

<style scoped>
.coverage{display:grid;grid-template-columns:auto minmax(90px,1fr) auto;gap:.35rem .55rem;align-items:center;margin-top:.6rem;padding:.55rem;border-radius:7px;background:#f4f9f9;font-size:.78rem}.coverage small{grid-column:1/-1;color:#667b80}.coverage-bar{height:.45rem;overflow:hidden;border-radius:999px;background:#dce9ea}.coverage-bar span{display:block;height:100%;border-radius:inherit;background:#238b71;transition:width .2s ease}
</style>
