<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { download } from '../export/download'
import type { PlanningTemplate } from '../domain/types'
import { getPlanningTemplates, registerLocalTemplate, removeLocalTemplate } from '../data/templates/registry'
const templates = ref<PlanningTemplate[]>([]); const message = ref(''); const error = ref('')
const refresh = (): void => { templates.value = getPlanningTemplates(); message.value = ''; error.value = '' }; onMounted(refresh)
function create(): void { const name = window.prompt('Name der neuen Vorlage:')?.trim(); if (!name) return; const template = registerLocalTemplate({ schemaVersion: 1, id: `user-${crypto.randomUUID().slice(0, 8)}`, name: { de: name }, version: '1.0.0', competencyFrameworkIds: [], source: { type: 'local' } }); refresh(); message.value = `Vorlage „${template.name.de}“ angelegt.` }
function exportTemplate(template: PlanningTemplate): void { download({ filename: `${template.id}.verlaufsplan-template.json`, mimeType: 'application/json;charset=utf-8', content: JSON.stringify(template, null, 2) }) }
function remove(template: PlanningTemplate): void { removeLocalTemplate(template.id); refresh(); message.value = 'Vorlage gelöscht.' }
async function importTemplate(event: Event): Promise<void> { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; try { const template = registerLocalTemplate(JSON.parse(await file.text())); refresh(); message.value = `Vorlage „${template.name.de}“ importiert.` } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Die Vorlage konnte nicht importiert werden.' } finally { input.value = '' } }
</script>
<template><main class="settings-shell"><header class="settings-header"><div><p class="eyebrow">Einstellungen</p><h1>Eigene Vorlagen</h1><p>Vorlagen sind lokale Benutzerinhalte. Das Projekt liefert keine fachgebundenen Vorlagen mit.</p></div><RouterLink class="secondary link-button" :to="{ name: 'home' }">← Zurück</RouterLink></header><section class="settings-card"><div class="section-heading with-action"><div><h2>Vorlagenbibliothek</h2><p>Vorlagen referenzieren committed Kompetenz- und Curriculumdaten ausschließlich über stabile IDs.</p></div><div class="template-actions"><button type="button" @click="create">Neue Vorlage</button><label class="file-label">Vorlage importieren<input type="file" accept="application/json,.json" @change="importTemplate"></label></div></div><p v-if="!templates.length" class="empty-state">Noch keine eigenen Vorlagen.</p><article v-for="template in templates" :key="template.id" class="template-card"><div><h3>{{ template.name.de }}</h3><small>{{ template.id }} · {{ template.competencyFrameworkIds.join(', ') || 'keine Referenzsysteme' }}</small></div><div class="template-actions"><button type="button" class="secondary" @click="exportTemplate(template)">Exportieren</button><button type="button" class="danger" @click="remove(template)">Löschen</button></div></article></section><p v-if="message" class="success-message">{{ message }}</p><p v-if="error" class="error-message">{{ error }}</p></main></template>
