<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { createId } from '../domain/factories'
import type { DashboardWidget, InventoryScope, MaterialResourceType, WorkspaceSettings } from '../domain/types'
import { WorkspaceRepository } from '../repositories/WorkspaceRepository'

const repository = new WorkspaceRepository()
const workspace = ref<WorkspaceSettings>()
const message = ref(''); const error = ref(''); const buildingName = ref(''); const roomName = ref(''); const roomBuildingId = ref('')
const inventoryName = ref(''); const inventoryQuantity = ref(''); const inventoryScope = ref<InventoryScope>('personal'); const inventoryBuildingId = ref(''); const inventoryRoomId = ref(''); const todoTitle = ref(''); const todoDate = ref('')
const draggedWidgetId = ref<string>()
const materialTypes: MaterialResourceType[] = ['physical', 'file', 'worksheet', 'link', 'interactive-html']
const inventoryType = ref<MaterialResourceType>('physical')
const roomsForInventory = computed(() => (workspace.value?.rooms ?? []).filter((room) => !inventoryBuildingId.value || room.buildingId === inventoryBuildingId.value))

async function load(): Promise<void> { try { workspace.value = await repository.get() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Arbeitsbereich konnte nicht geladen werden.' } }
onMounted(() => void load())
async function save(note?: string): Promise<void> { if (!workspace.value) return; try { workspace.value = await repository.save(workspace.value); message.value = note ?? 'Einstellungen gespeichert.'; error.value = '' } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Einstellungen konnten nicht gespeichert werden.' } }
async function addBuilding(): Promise<void> { if (!workspace.value || !buildingName.value.trim()) return; workspace.value.buildings.push({ id: createId(), name: buildingName.value.trim() }); buildingName.value = ''; await save('Gebäude gespeichert.') }
async function addRoom(): Promise<void> { if (!workspace.value || !roomName.value.trim() || !roomBuildingId.value) return; workspace.value.rooms.push({ id: createId(), buildingId: roomBuildingId.value, name: roomName.value.trim() }); roomName.value = ''; await save('Raum gespeichert.') }
async function addInventory(): Promise<void> { if (!workspace.value || !inventoryName.value.trim()) return; const scope = inventoryScope.value; if ((scope === 'building' || scope === 'room') && !inventoryBuildingId.value) { error.value = 'Für Gebäude- oder Raumbestand wählen Sie ein Gebäude.'; return } if (scope === 'room' && !inventoryRoomId.value) { error.value = 'Für Raumbestand wählen Sie einen Raum.'; return }; workspace.value.inventoryMaterials.push({ id: createId(), name: inventoryName.value.trim(), quantity: inventoryQuantity.value || undefined, resourceType: inventoryType.value, scope, buildingId: scope === 'personal' ? undefined : inventoryBuildingId.value, roomId: scope === 'room' ? inventoryRoomId.value : undefined }); inventoryName.value = ''; inventoryQuantity.value = ''; await save('Bestandsmaterial gespeichert.') }
async function addTodo(): Promise<void> { if (!workspace.value || !todoTitle.value.trim()) return; workspace.value.todos.push({ id: createId(), title: todoTitle.value.trim(), dueDate: todoDate.value || undefined, completed: false }); todoTitle.value = ''; todoDate.value = ''; await save('Aufgabe gespeichert.') }
async function remove(kind: 'buildings' | 'rooms' | 'inventoryMaterials' | 'todos', id: string): Promise<void> { if (!workspace.value) return; if (kind === 'buildings') { workspace.value.buildings = workspace.value.buildings.filter((item) => item.id !== id); workspace.value.rooms = workspace.value.rooms.filter((item) => item.buildingId !== id) } else workspace.value[kind] = workspace.value[kind].filter((item) => item.id !== id) as never; await save('Eintrag entfernt.') }
async function toggleTodo(id: string): Promise<void> { if (!workspace.value) return; const todo = workspace.value.todos.find((item) => item.id === id); if (todo) { todo.completed = !todo.completed; await save('Aufgabe aktualisiert.') } }
async function toggleWidget(widget: DashboardWidget): Promise<void> { widget.enabled = !widget.enabled; await save('Dashboard gespeichert.') }
async function reorder(targetId: string): Promise<void> { if (!workspace.value || !draggedWidgetId.value || draggedWidgetId.value === targetId) return; const items = [...workspace.value.dashboard].sort((left, right) => left.order - right.order); const source = items.findIndex((item) => item.id === draggedWidgetId.value); const target = items.findIndex((item) => item.id === targetId); const [widget] = items.splice(source, 1); items.splice(target, 0, widget); workspace.value.dashboard = items.map((item, index) => ({ ...item, order: index })); draggedWidgetId.value = undefined; await save('Widget-Reihenfolge gespeichert.') }
</script>

<template>
  <main class="settings-shell" v-if="workspace">
    <header class="settings-header"><div><p class="eyebrow">Einstellungen</p><h1>Arbeitsbereich & Dashboard</h1><p>Ordnen Sie Startseiten-Widgets an und verwalten Sie lokale Räume, Aufgaben und Materialbestände.</p></div><RouterLink class="secondary link-button" :to="{ name: 'home' }">Zurück</RouterLink></header>
    <section class="settings-card"><div class="section-heading"><h2>Dashboard-Widgets</h2><p>Widgets per Ziehen anordnen. Kalenderansicht und Anzahl der nächsten Einträge sind pro Widget einstellbar.</p></div><div class="widget-settings"><article v-for="widget in [...workspace.dashboard].sort((a, b) => a.order - b.order)" :key="widget.id" class="widget-setting" draggable="true" @dragstart="draggedWidgetId = widget.id" @dragover.prevent @drop.prevent="reorder(widget.id)"><span class="drag-handle">↕</span><strong>{{ widget.id === 'calendar' ? 'Kalender' : widget.id === 'upcoming-plans' ? 'Nächste Verlaufspläne' : widget.id === 'upcoming-todos' ? 'Nächste Aufgaben' : 'Materialvorbereitung für morgen' }}</strong><label class="switch"><input type="checkbox" :checked="widget.enabled" @change="toggleWidget(widget)">Anzeigen</label><label v-if="widget.id === 'calendar'">Ansicht<select v-model="widget.calendarView" @change="save('Kalenderansicht gespeichert.')"><option value="day">Tag</option><option value="week">Woche</option><option value="month">Monat</option></select></label><label v-if="widget.id === 'upcoming-plans' || widget.id === 'upcoming-todos'">Anzahl<select v-model.number="widget.limit" @change="save('Anzahl gespeichert.')"><option v-for="number in [3, 5, 8, 10, 15]" :key="number" :value="number">{{ number }}</option></select></label></article></div></section>
    <section class="settings-card"><div class="section-heading"><h2>Gebäude und Räume</h2><p>Diese Auswahl steht beim Anlegen und in den allgemeinen Angaben einer Planung bereit.</p></div><div class="settings-two-column"><form class="stack-form" @submit.prevent="addBuilding"><label>Gebäude<input v-model="buildingName" placeholder="z. B. Hauptgebäude"></label><button type="submit">Gebäude hinzufügen</button></form><form class="stack-form" @submit.prevent="addRoom"><label>Gebäude<select v-model="roomBuildingId" required><option value="">Auswählen</option><option v-for="building in workspace.buildings" :key="building.id" :value="building.id">{{ building.name }}</option></select></label><label>Raum<input v-model="roomName" placeholder="z. B. 2.14"></label><button type="submit">Raum hinzufügen</button></form></div><div class="settings-list"><article v-for="building in workspace.buildings" :key="building.id"><div><strong>{{ building.name }}</strong><small>{{ workspace.rooms.filter((room) => room.buildingId === building.id).map((room) => room.name).join(', ') || 'Noch keine Räume' }}</small></div><button type="button" class="danger" @click="remove('buildings', building.id)">Entfernen</button></article></div></section>
    <section class="settings-card"><div class="section-heading"><h2>Materialbestand</h2><p>Bestand ist entweder Ihrem Privatbestand, einem Gebäude oder einem konkreten Raum zugeordnet und kann anschließend in Planungen übernommen werden.</p></div><form class="inventory-form" @submit.prevent="addInventory"><label>Bezeichnung<input v-model="inventoryName" required placeholder="z. B. Beamer"></label><label>Menge<input v-model="inventoryQuantity" placeholder="z. B. 1"></label><label>Typ<select v-model="inventoryType"><option v-for="type in materialTypes" :key="type" :value="type">{{ type }}</option></select></label><label>Bestand<select v-model="inventoryScope"><option value="personal">Referenten-/Lehrerprivatbestand</option><option value="building">Gebäude</option><option value="room">Raum</option></select></label><label v-if="inventoryScope !== 'personal'">Gebäude<select v-model="inventoryBuildingId"><option value="">Auswählen</option><option v-for="building in workspace.buildings" :key="building.id" :value="building.id">{{ building.name }}</option></select></label><label v-if="inventoryScope === 'room'">Raum<select v-model="inventoryRoomId"><option value="">Auswählen</option><option v-for="room in roomsForInventory" :key="room.id" :value="room.id">{{ room.name }}</option></select></label><button type="submit">Bestandsmaterial speichern</button></form><div class="settings-list"><article v-for="material in workspace.inventoryMaterials" :key="material.id"><div><strong>{{ material.name }}</strong><small>{{ material.scope === 'personal' ? 'Privatbestand' : material.scope === 'room' ? 'Raumbestand' : 'Gebäudebestand' }}{{ material.quantity ? ` · ${material.quantity}` : '' }}</small></div><button type="button" class="danger" @click="remove('inventoryMaterials', material.id)">Entfernen</button></article></div></section>
    <section class="settings-card"><div class="section-heading"><h2>Aufgaben</h2><p>Aufgaben mit Datum erscheinen im Dashboard und im Kalender.</p></div><form class="settings-two-column" @submit.prevent="addTodo"><label>Aufgabe<input v-model="todoTitle" required placeholder="z. B. Arbeitsblätter drucken"></label><label>Fällig am<input v-model="todoDate" type="date"></label><button type="submit">Aufgabe hinzufügen</button></form><div class="settings-list"><article v-for="todo in workspace.todos" :key="todo.id"><label class="todo-toggle"><input type="checkbox" :checked="todo.completed" @change="toggleTodo(todo.id)"><span :class="{ completed: todo.completed }">{{ todo.title }} <small>{{ todo.dueDate || 'ohne Termin' }}</small></span></label><button type="button" class="danger" @click="remove('todos', todo.id)">Entfernen</button></article></div></section>
    <p v-if="message" class="success-message">{{ message }}</p><p v-if="error" class="error-message">{{ error }}</p>
  </main>
  <main v-else class="loading">Arbeitsbereich wird geladen ...</main>
</template>
