import { z } from 'zod'

const sourceRef = z.object({ sourceId: z.string().min(1), page: z.number().int().positive().optional(), section: z.string().optional(), heading: z.string().optional(), table: z.string().optional(), note: z.string().optional() })
const gradeRange = z.object({ from: z.number().int().min(1), to: z.number().int().min(1) }).refine((range) => range.from <= range.to)
const review = z.enum(['verified', 'machine-extracted', 'needs-review'])
export const CurriculumSourceSchema = z.object({ id: z.string().min(1), publisher: z.string().min(1), title: z.string().min(1), publicationYear: z.number().int().optional(), version: z.string().optional(), sourceUrl: z.string().url(), retrievedAt: z.string().date(), sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(), license: z.object({ name: z.string().optional(), url: z.string().url().optional(), redistribution: z.boolean().optional(), notes: z.string().optional() }).optional() })
export const CurriculumSchema = z.object({
  id: z.string().min(1), jurisdiction: z.literal('TH'), schoolType: z.literal('gymnasium'), subject: z.object({ id: z.string().min(1), name: z.object({ de: z.string().min(1), en: z.string().optional() }), aliases: z.array(z.string()).optional(), category: z.string().optional() }), title: z.string().min(1), version: z.string().min(1), publicationYear: z.number().int().optional(), sourceId: z.string().min(1),
  applicability: z.array(z.object({ schoolYearFrom: z.string().regex(/^\d{4}\/\d{2}$/).optional(), schoolYearTo: z.string().regex(/^\d{4}\/\d{2}$/).optional(), grades: z.array(z.number().int().min(1)).min(1), phase: z.enum(['planned', 'trial', 'active', 'transition', 'expired']).optional(), courseType: z.string().optional() })).min(1),
  competencyDomains: z.array(z.object({ id: z.string().min(1), title: z.string().min(1), order: z.number().int().positive(), sourceRef })).min(1),
  competencies: z.array(z.object({ id: z.string().min(1), curriculumId: z.string().min(1), domainId: z.string().optional(), learningAreaId: z.string().optional(), gradeRange: gradeRange.optional(), text: z.string().min(1), normalizedLabel: z.string().optional(), order: z.number().int().positive(), mandatory: z.boolean().optional(), sourceRef, reviewStatus: review, tags: z.array(z.string()).optional() })).min(1),
  learningAreas: z.array(z.object({ id: z.string().min(1), curriculumId: z.string().min(1), parentId: z.string().optional(), gradeRange, title: z.string().min(1), description: z.string().optional(), order: z.number().int().positive(), competencyIds: z.array(z.string()), contentPointIds: z.array(z.string()), sourceRef })).min(1),
  contentPoints: z.array(z.object({ id: z.string().min(1), curriculumId: z.string().min(1), learningAreaId: z.string().min(1), title: z.string().min(1), description: z.string().optional(), order: z.number().int().positive(), mandatory: z.boolean().optional(), kind: z.enum(['core-content', 'content-focus', 'example', 'optional', 'regional-reference', 'cross-curricular']).optional(), sourceRef, reviewStatus: review })).min(1),
  relations: z.array(z.object({ id: z.string().min(1), fromId: z.string().min(1), toId: z.string().min(1), type: z.enum(['develops', 'applies-to', 'belongs-to', 'requires', 'suggested-with', 'cross-reference']) })),
})
