<script setup lang="ts">
import { computed } from 'vue'
import type { PollOption, PollTemplate, PollWidget, WidgetColorSet } from '../../domain/types'
import { widgetColorSets, widgetColorStyle } from '../widgetDesign'

const props = withDefaults(defineProps<{ poll: PollWidget; editing?: boolean; votes?: Record<string, number>; showResults?: boolean; allowVoting?: boolean }>(), { editing: false, votes: () => ({}), showResults: false, allowVoting: false })
const emit = defineEmits<{ beginChange: []; changed: []; finish: []; vote: [optionId: string] }>()
const total = computed(() => Object.values(props.votes).reduce((sum, votes) => sum + votes, 0))
const template = computed(() => props.poll.template ?? 'karten')
const colorSet = computed(() => props.poll.colorSet ?? 'ozean')
const templates: Array<{ id: PollTemplate; label: string }> = [{ id: 'karten', label: 'Karten' }, { id: 'podium', label: 'Podium' }, { id: 'kompakt', label: 'Kompakt' }]
function changeOption(option: PollOption, event: Event): void { emit('beginChange'); option.label = (event.target as HTMLInputElement).value; emit('changed') }
function changeQuestion(event: Event): void { emit('beginChange'); props.poll.question = (event.target as HTMLInputElement).value; emit('changed') }
function setType(event: Event): void { emit('beginChange'); props.poll.type = (event.target as HTMLSelectElement).value as PollWidget['type']; props.poll.options = props.poll.type === 'yes-no' ? [{ id: crypto.randomUUID(), label: 'Ja' }, { id: crypto.randomUUID(), label: 'Nein' }] : [{ id: crypto.randomUUID(), label: 'Option 1' }, { id: crypto.randomUUID(), label: 'Option 2' }, { id: crypto.randomUUID(), label: 'Option 3' }]; emit('changed') }
function setTemplate(value: PollTemplate): void { emit('beginChange'); props.poll.template = value; emit('changed') }
function setColorSet(value: WidgetColorSet): void { emit('beginChange'); props.poll.colorSet = value; emit('changed') }
function addOption(): void { emit('beginChange'); props.poll.options.push({ id: crypto.randomUUID(), label: `Option ${props.poll.options.length + 1}` }); emit('changed') }
function removeOption(id: string): void { if (props.poll.options.length <= 2) return; emit('beginChange'); props.poll.options = props.poll.options.filter((option) => option.id !== id); emit('changed') }
function percentage(optionId: string): number { return total.value ? Math.round(((props.votes[optionId] ?? 0) / total.value) * 100) : 0 }
</script>

<template>
  <section class="poll-widget" :class="[`template-${template}`, { editing, results: showResults }]" :style="widgetColorStyle(colorSet)" @pointerdown.stop>
    <template v-if="editing">
      <header class="poll-composer"><span>Abstimmung gestalten</span><div class="poll-choice"><button v-for="item in templates" :key="item.id" type="button" :class="{ selected: template === item.id }" @click.stop="setTemplate(item.id)">{{ item.label }}</button></div><div class="poll-colors"><button v-for="palette in widgetColorSets" :key="palette.id" type="button" :class="{ selected: colorSet === palette.id }" :aria-label="`Farbset ${palette.label}`" :title="palette.label" @click.stop="setColorSet(palette.id)"><i :style="{ background: palette.accent }" /></button></div></header>
      <div class="poll-settings"><label>Frage<input :value="poll.question" aria-label="Abstimmungsfrage" @input="changeQuestion" /></label><label>Art<select :value="poll.type" @change="setType"><option value="yes-no">Ja / Nein</option><option value="multiple-choice">Mehrfachauswahl</option></select></label></div>
    </template>
    <h2 v-else>{{ poll.question }}</h2>
    <div class="poll-options"><template v-for="option in poll.options" :key="option.id"><label v-if="editing" class="poll-option-edit"><input :value="option.label" :aria-label="`Antwort ${option.label}`" @input="changeOption(option, $event)" /><button v-if="poll.type === 'multiple-choice'" type="button" :disabled="poll.options.length <= 2" @click.stop="removeOption(option.id)">×</button></label><button v-else type="button" class="poll-option" :disabled="!allowVoting || showResults" @click.stop="emit('vote', option.id)"><span>{{ option.label }}</span><span v-if="showResults" class="poll-result"><i :style="{ width: `${percentage(option.id)}%` }" />{{ percentage(option.id) }} %</span></button></template></div>
    <footer v-if="editing" class="poll-tools" role="toolbar" aria-label="Abstimmung bearbeiten"><button v-if="poll.type === 'multiple-choice'" type="button" @click.stop="addOption">+ Antwort</button><button type="button" class="finish" @click.stop="emit('finish')">Bearbeitung beenden</button></footer>
    <p v-else-if="showResults" class="vote-total">{{ total }} Stimme{{ total === 1 ? '' : 'n' }}</p><p v-else-if="allowVoting" class="vote-hint">Wähle eine Antwort.</p>
  </section>
</template>

<style scoped>
.poll-widget { display: grid; align-content: center; gap: clamp(8px, 1.3cqw, 16px); width: 100%; height: 100%; padding: 8%; color: var(--widget-text); background: radial-gradient(circle at 13% 9%, #fff8, transparent 30%), linear-gradient(145deg, var(--widget-surface), var(--widget-surface-strong)); container-type: inline-size; text-align: center; }.poll-widget h2 { margin: 0; font-size: clamp(16px, 3.2cqw, 36px); }.poll-options { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: clamp(8px, 1.2cqw, 16px); }.poll-option { display: grid; gap: .45em; min-height: 3em; padding: .7em; color: #fff; background: var(--widget-accent-strong); border: 2px solid color-mix(in srgb, var(--widget-accent) 70%, #fff); border-radius: .72em; box-shadow: 0 .35em .8em color-mix(in srgb, var(--widget-accent-strong) 28%, transparent); font: inherit; font-size: clamp(12px, 2cqw, 22px); font-weight: 800; }.poll-option:not(:disabled):hover { background: var(--widget-accent); transform: translateY(-2px); }.poll-option:disabled { cursor: default; }.poll-result { position: relative; overflow: hidden; padding: .2em .4em; background: #ffffff2b; border-radius: 999px; font-size: .75em; }.poll-result i { position: absolute; inset: 0 auto 0 0; background: var(--widget-accent-soft); opacity: .75; }.poll-result { isolation: isolate; }.poll-result::after { content: ''; position: absolute; inset: 0; z-index: -1; }.template-podium .poll-options { grid-template-columns: 1fr; max-width: 72%; margin: auto; }.template-podium .poll-option { grid-template-columns: minmax(0, 1fr) minmax(120px, .8fr); align-items: center; border-radius: .35em; }.template-kompakt { background: var(--widget-surface); }.template-kompakt .poll-option { min-height: 0; padding: .45em .55em; border-radius: .35em; box-shadow: none; }
.poll-composer { display: flex; align-items: center; flex-wrap: wrap; gap: .45em; padding: .55em .65em; color: var(--widget-text); background: #ffffffd6; border: 1px solid color-mix(in srgb, var(--widget-accent) 25%, #fff); border-radius: .7em; font-size: clamp(10px, 1.6cqw, 16px); font-weight: 850; text-align: left; }.poll-choice { display: flex; gap: .2em; }.poll-choice button { padding: .28em .45em; color: var(--widget-muted); background: var(--widget-surface); border: 1px solid transparent; border-radius: .35em; font: inherit; font-size: .8em; }.poll-choice button.selected { color: #fff; background: var(--widget-accent-strong); }.poll-colors { display: flex; gap: .2em; margin-left: auto; }.poll-colors button { display: grid; width: 1.6em; height: 1.6em; padding: .18em; place-items: center; background: #fff; border: 1px solid transparent; border-radius: 50%; }.poll-colors i { width: 100%; height: 100%; border-radius: 50%; }.poll-colors button.selected { border-color: var(--widget-accent-strong); box-shadow: 0 0 0 2px var(--widget-accent-strong); }.poll-settings { display: grid; grid-template-columns: minmax(0, 1fr) minmax(130px, .42fr); gap: .6em; text-align: left; }.poll-settings label { display: grid; gap: .2em; font-size: clamp(10px, 1.5cqw, 15px); font-weight: 800; }.poll-widget input, .poll-widget select { min-width: 0; padding: .4em; color: var(--widget-text); background: #fff; border: 1px solid color-mix(in srgb, var(--widget-accent) 35%, #fff); border-radius: .35em; font: inherit; }.poll-option-edit { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: .25em; }.poll-tools { display: flex; justify-content: center; gap: .5em; }.poll-tools button, .poll-option-edit button { padding: .35em .6em; color: var(--widget-accent-strong); background: #fff; border: 1px solid color-mix(in srgb, var(--widget-accent) 45%, #fff); border-radius: .35em; font: inherit; font-weight: 800; }.poll-tools .finish { color: #fff; background: var(--widget-accent-strong); border-color: var(--widget-accent-strong); }.vote-total, .vote-hint { margin: 0; color: var(--widget-muted); font-size: clamp(10px, 1.7cqw, 16px); font-weight: 700; }
</style>
