<script setup lang="ts">
import { computed } from 'vue'
import type { TimelineEntry, TimelineTemplate, TimelineWidget, WidgetColorSet } from '../../domain/types'
import { widgetColorSets, widgetColorStyle } from '../widgetDesign'

const props = withDefaults(defineProps<{ timeline: TimelineWidget; editing?: boolean }>(), { editing: false })
const emit = defineEmits<{ beginChange: []; changed: []; finish: [] }>()
const template = computed(() => props.timeline.template ?? 'chronik')
const colorSet = computed(() => props.timeline.colorSet ?? 'ozean')
const templates: Array<{ id: TimelineTemplate; label: string; description: string }> = [
  { id: 'chronik', label: 'Chronik', description: 'Karten entlang einer lebendigen Achse' },
  { id: 'museum', label: 'Museum', description: 'Ruhig, editorial und erzählerisch' },
  { id: 'minimal', label: 'Minimal', description: 'Reduziert für dichte Fakten' },
]

function changeEntry(entry: TimelineEntry, key: 'date' | 'title' | 'description', event: Event): void {
  emit('beginChange')
  entry[key] = (event.target as HTMLInputElement | HTMLTextAreaElement).value
  emit('changed')
}
function addEntry(): void {
  emit('beginChange')
  props.timeline.entries.push({ id: crypto.randomUUID(), date: 'Jahr', title: 'Neues Ereignis', description: 'Historischer Kontext' })
  emit('changed')
}
function removeEntry(id: string): void {
  if (props.timeline.entries.length <= 1) return
  emit('beginChange')
  props.timeline.entries = props.timeline.entries.filter((entry) => entry.id !== id)
  emit('changed')
}
function setOrientation(orientation: TimelineWidget['orientation']): void { emit('beginChange'); props.timeline.orientation = orientation; emit('changed') }
function setTemplate(value: TimelineTemplate): void { emit('beginChange'); props.timeline.template = value; emit('changed') }
function setColorSet(value: WidgetColorSet): void { emit('beginChange'); props.timeline.colorSet = value; emit('changed') }
</script>

<template>
  <section class="timeline-widget" :class="[timeline.orientation, `template-${template}`, { editing }]" :style="{ ...widgetColorStyle(colorSet), '--timeline-count': timeline.entries.length }" @pointerdown.stop>
    <template v-if="editing">
      <header class="timeline-composer">
        <div class="composer-heading"><span class="composer-kicker">Historischer Zeitstrahl</span><strong>{{ timeline.entries.length }} Ereignisse</strong></div>
        <div class="composer-row"><span class="composer-label">Vorlage</span><div class="choice-group templates"><button v-for="item in templates" :key="item.id" type="button" :class="{ selected: template === item.id }" :title="item.description" @click.stop="setTemplate(item.id)">{{ item.label }}</button></div></div>
        <div class="composer-row"><span class="composer-label">Farben</span><div class="choice-group colors"><button v-for="palette in widgetColorSets" :key="palette.id" type="button" :class="{ selected: colorSet === palette.id }" :aria-label="`Farbset ${palette.label}`" :title="palette.label" @click.stop="setColorSet(palette.id)"><i :style="{ background: palette.accent }" /></button></div><span class="composer-label orientation-label">Ausrichtung</span><div class="choice-group"><button type="button" :class="{ selected: timeline.orientation === 'horizontal' }" @click.stop="setOrientation('horizontal')">Horizontal</button><button type="button" :class="{ selected: timeline.orientation === 'vertical' }" @click.stop="setOrientation('vertical')">Vertikal</button></div></div>
      </header>
      <div class="timeline-edit-list" aria-label="Ereignisse bearbeiten">
        <article v-for="(entry, index) in timeline.entries" :key="entry.id" class="timeline-edit-card">
          <div class="edit-index"><i :style="{ background: entry.color || 'var(--widget-accent)' }" /><span>{{ String(index + 1).padStart(2, '0') }}</span></div>
          <div class="edit-fields"><label>ZEITPUNKT<input class="timeline-date" :value="entry.date" :aria-label="`Zeitpunkt fuer ${entry.title}`" placeholder="Jahr oder Datum" @input="changeEntry(entry, 'date', $event)" /></label><label>EREIGNIS<input class="timeline-title" :value="entry.title" :aria-label="`Titel fuer ${entry.date}`" placeholder="Historisches Ereignis" @input="changeEntry(entry, 'title', $event)" /></label><label class="description-field">KONTEXT<textarea :value="entry.description" :aria-label="`Beschreibung fuer ${entry.title}`" placeholder="Historischer Kontext" rows="1" @input="changeEntry(entry, 'description', $event)" /></label></div>
          <button class="remove-entry" type="button" :disabled="timeline.entries.length <= 1" :aria-label="`Ereignis ${entry.title} entfernen`" title="Ereignis entfernen" @click.stop="removeEntry(entry.id)">×</button>
        </article>
      </div>
      <footer class="timeline-composer-footer timeline-tools"><button type="button" class="add-entry" @click.stop="addEntry">+ Ereignis</button><button type="button" class="finish-edit" @click.stop="emit('finish')">Bearbeitung beenden</button></footer>
    </template>
    <template v-else>
      <div class="timeline-track" aria-hidden="true" />
      <article v-for="entry in timeline.entries" :key="entry.id" class="timeline-entry"><span class="timeline-marker" :style="{ background: entry.color || 'var(--widget-accent)' }" aria-hidden="true" /><div class="timeline-card"><small>{{ entry.date }}</small><strong>{{ entry.title }}</strong><p v-if="entry.description">{{ entry.description }}</p></div></article>
    </template>
  </section>
</template>

<style scoped>
.timeline-widget { position: relative; display: grid; min-width: 0; min-height: 0; width: 100%; height: 100%; padding: 6% 5%; overflow: hidden; color: var(--widget-text); background: radial-gradient(circle at 12% 8%, #fff 0, #fff9 22%, transparent 40%), linear-gradient(135deg, var(--widget-surface), var(--widget-surface-strong)); container-type: inline-size; }.timeline-widget.horizontal { grid-template-columns: repeat(var(--timeline-count, 3), minmax(0, 1fr)); }.timeline-track { position: absolute; z-index: 0; top: 50%; right: 7%; left: 7%; height: max(4px, .5cqw); border-radius: 999px; background: linear-gradient(90deg, var(--widget-accent), color-mix(in srgb, var(--widget-accent) 45%, #8c7be8)); box-shadow: 0 2px 12px color-mix(in srgb, var(--widget-accent) 32%, transparent); }.timeline-entry { position: relative; z-index: 1; display: grid; grid-template-rows: 1fr auto 1fr; min-width: 0; padding: 0 clamp(5px, 1.2cqw, 16px); text-align: center; }.timeline-marker { z-index: 2; grid-row: 2; justify-self: center; width: clamp(18px, 3.6cqw, 42px); height: clamp(18px, 3.6cqw, 42px); border: clamp(3px, .52cqw, 6px) solid #fff; border-radius: 50%; box-shadow: 0 0 0 clamp(3px, .45cqw, 5px) color-mix(in srgb, var(--widget-accent) 27%, transparent), 0 7px 13px #15565b2b; }.timeline-card { display: grid; gap: .28em; min-width: 0; padding: .62em .75em; color: var(--widget-text); background: #fffffff0; border: 1px solid color-mix(in srgb, var(--widget-accent) 28%, #fff); border-radius: .72em; box-shadow: 0 .38em .9em color-mix(in srgb, var(--widget-accent-strong) 16%, transparent); }.timeline-widget.horizontal .timeline-entry:nth-of-type(odd) .timeline-card { grid-row: 1; align-self: end; margin-bottom: 1.1em; }.timeline-widget.horizontal .timeline-entry:nth-of-type(even) .timeline-card { grid-row: 3; align-self: start; margin-top: 1.1em; }.timeline-entry small { color: var(--widget-accent-strong); font-size: clamp(9px, 1.65cqw, 15px); font-weight: 900; letter-spacing: .07em; }.timeline-entry strong { overflow: hidden; font-size: clamp(10px, 2cqw, 19px); line-height: 1.15; text-overflow: ellipsis; }.timeline-entry p { display: -webkit-box; margin: 0; overflow: hidden; color: var(--widget-muted); font-size: clamp(8px, 1.48cqw, 14px); line-height: 1.3; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }
.template-museum { background: linear-gradient(135deg, color-mix(in srgb, var(--widget-surface) 72%, #fff7e9), var(--widget-surface-strong)); }.template-museum .timeline-track { height: max(2px, .27cqw); background: var(--widget-accent-strong); box-shadow: none; }.template-museum .timeline-marker { border-radius: 32% 32% 32% 0; transform: rotate(-45deg); }.template-museum .timeline-card { border-radius: .22em; box-shadow: 0 .25em .5em #1a263018; }.template-minimal { background: var(--widget-surface); }.template-minimal .timeline-card { padding: .35em .45em; background: transparent; border: 0; box-shadow: none; }.template-minimal .timeline-marker { width: clamp(12px, 2.4cqw, 26px); height: clamp(12px, 2.4cqw, 26px); box-shadow: 0 0 0 2px #fff; }
.timeline-widget.vertical { grid-template-columns: 1fr; grid-template-rows: repeat(var(--timeline-count, 3), minmax(0, 1fr)); padding: 6% 7% 6% 17%; }.timeline-widget.vertical .timeline-track { top: 9%; bottom: 9%; left: 12%; width: max(4px, .5cqw); height: auto; background: linear-gradient(var(--widget-accent), color-mix(in srgb, var(--widget-accent) 45%, #8c7be8)); }.timeline-widget.vertical .timeline-entry { grid-template-columns: clamp(24px, 4.5cqw, 52px) minmax(0, 1fr); grid-template-rows: 1fr; align-items: center; padding: clamp(3px, .55cqw, 7px) 0; text-align: left; }.timeline-widget.vertical .timeline-marker { grid-row: 1; grid-column: 1; margin: 0; }.timeline-widget.vertical .timeline-card { grid-row: 1; grid-column: 2; align-self: center; }
.timeline-widget.editing { display: grid; grid-template-rows: auto minmax(0, 1fr) auto; gap: .6em; padding: clamp(10px, 2cqw, 22px); background: linear-gradient(140deg, color-mix(in srgb, var(--widget-surface) 84%, #fff), var(--widget-surface-strong)); }.timeline-composer { display: grid; gap: .45em; padding: .75em .85em; background: #ffffffd9; border: 1px solid color-mix(in srgb, var(--widget-accent) 28%, #fff); border-radius: .85em; box-shadow: 0 .45em 1.2em color-mix(in srgb, var(--widget-accent-strong) 13%, transparent); }.composer-heading { display: flex; justify-content: space-between; gap: .5em; align-items: baseline; }.composer-kicker { color: var(--widget-accent-strong); font-size: .72em; font-weight: 900; letter-spacing: .1em; text-transform: uppercase; }.composer-heading strong { font-size: .9em; }.composer-row { display: flex; align-items: center; flex-wrap: wrap; gap: .35em; }.composer-label { min-width: 3.7em; color: var(--widget-muted); font-size: .72em; font-weight: 800; }.orientation-label { margin-left: auto; }.choice-group { display: flex; gap: .22em; }.choice-group button { padding: .32em .55em; color: var(--widget-muted); background: var(--widget-surface); border: 1px solid transparent; border-radius: .38em; font: inherit; font-size: .76em; font-weight: 800; }.choice-group button.selected { color: #fff; background: var(--widget-accent-strong); border-color: var(--widget-accent-strong); box-shadow: 0 2px 6px color-mix(in srgb, var(--widget-accent-strong) 28%, transparent); }.choice-group.colors button { display: grid; width: 1.65em; height: 1.65em; padding: .2em; place-items: center; border-radius: 50%; }.choice-group.colors button i { width: 100%; height: 100%; border-radius: 50%; }.choice-group.colors button.selected { background: #fff; border-color: var(--widget-accent-strong); box-shadow: 0 0 0 2px var(--widget-accent-strong); }
.timeline-edit-list { display: grid; align-content: start; gap: .48em; min-height: 0; overflow: auto; padding: .15em .2em .15em 0; }.timeline-edit-card { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; gap: .6em; align-items: center; padding: .62em .72em; background: #ffffffe8; border: 1px solid color-mix(in srgb, var(--widget-accent) 20%, #fff); border-radius: .72em; box-shadow: 0 .2em .6em #1538300e; }.edit-index { display: grid; justify-items: center; gap: .25em; min-width: 2em; color: var(--widget-muted); font-size: .67em; font-weight: 900; }.edit-index i { width: .78em; height: .78em; border-radius: 50%; box-shadow: 0 0 0 .2em var(--widget-accent-soft); }.edit-fields { display: grid; grid-template-columns: minmax(74px, .35fr) minmax(0, 1fr) minmax(0, 1.2fr); gap: .5em; }.edit-fields label { display: grid; gap: .2em; color: var(--widget-muted); font-size: .62em; font-weight: 900; letter-spacing: .06em; }.edit-fields input, .edit-fields textarea { box-sizing: border-box; width: 100%; min-width: 0; padding: .35em .45em; resize: vertical; color: var(--widget-text); background: var(--widget-surface); border: 1px solid color-mix(in srgb, var(--widget-accent) 25%, #fff); border-radius: .38em; font: inherit; font-size: 1.15em; letter-spacing: 0; }.edit-fields textarea { min-height: 2.05em; }.remove-entry { width: 2em; aspect-ratio: 1; color: #a43f50; background: #fff1f2; border: 1px solid #f3c6cd; border-radius: .45em; font-size: 1.1em; font-weight: 900; }.remove-entry:disabled { visibility: hidden; }.timeline-composer-footer { display: flex; justify-content: space-between; gap: .5em; }.timeline-composer-footer button { padding: .55em .8em; border-radius: .5em; font: inherit; font-weight: 850; }.add-entry { color: var(--widget-accent-strong); background: #fff; border: 1px solid color-mix(in srgb, var(--widget-accent) 42%, #fff); }.finish-edit { color: #fff; background: var(--widget-accent-strong); border: 1px solid var(--widget-accent-strong); }.timeline-widget.editing.vertical { grid-template-columns: none; grid-template-rows: auto minmax(0, 1fr) auto; padding: clamp(10px, 2cqw, 22px); }.timeline-widget.editing .timeline-track, .timeline-widget.editing .timeline-entry { display: none; }
@container (max-width: 620px) { .edit-fields { grid-template-columns: 1fr 1fr; }.edit-fields .description-field { grid-column: 1 / -1; }.orientation-label { margin-left: 0; }.templates button:not(.selected) { display: none; } }
</style>
